// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/escalation.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EscalateRequest, EscalateResponse, ResolveEscalationRequest, ResolveEscalationResponse } from "./escalation_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.EscalationService
 */
export declare const EscalationService: {
  readonly typeName: "routeiq.v1.control.EscalationService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.control.EscalationService.Escalate
     */
    readonly escalate: {
      readonly name: "Escalate",
      readonly I: typeof EscalateRequest,
      readonly O: typeof EscalateResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.EscalationService.ResolveEscalation
     */
    readonly resolveEscalation: {
      readonly name: "ResolveEscalation",
      readonly I: typeof ResolveEscalationRequest,
      readonly O: typeof ResolveEscalationResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

