// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/escalation.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/control/escalation.proto.
 */
export const file_routeiq_v1_control_escalation = /*@__PURE__*/
  fileDesc("CiNyb3V0ZWlxL3YxL2NvbnRyb2wvZXNjYWxhdGlvbi5wcm90bxIScm91dGVpcS52MS5jb250cm9sIoYBCg9Fc2NhbGF0ZVJlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoCRIOCgZyZWFzb24YAiABKAkSFwoPY29udGV4dF9zdW1tYXJ5GAMgASgJEjYKB3VyZ2VuY3kYBCABKA4yJS5yb3V0ZWlxLnYxLmNvbnRyb2wuRXNjYWxhdGlvblVyZ2VuY3kijQEKEEVzY2FsYXRlUmVzcG9uc2USFQoNZXNjYWxhdGlvbl9pZBgBIAEoCRIyCgVzdGF0ZRgCIAEoDjIjLnJvdXRlaXEudjEuY29udHJvbC5Fc2NhbGF0aW9uU3RhdGUSLgoKY3JlYXRlZF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiVwoYUmVzb2x2ZUVzY2FsYXRpb25SZXF1ZXN0EhUKDWVzY2FsYXRpb25faWQYASABKAkSEgoKcmVzb2x1dGlvbhgCIAEoCRIQCghhcHByb3ZlZBgDIAEoCCItChlSZXNvbHZlRXNjYWxhdGlvblJlc3BvbnNlEhAKCGFjY2VwdGVkGAEgASgIKmQKEUVzY2FsYXRpb25VcmdlbmN5EiIKHkVTQ0FMQVRJT05fVVJHRU5DWV9VTlNQRUNJRklFRBAAEgcKA0xPVxABEgoKBk1FRElVTRACEggKBEhJR0gQAxIMCghDUklUSUNBTBAEKmwKD0VzY2FsYXRpb25TdGF0ZRIgChxFU0NBTEFUSU9OX1NUQVRFX1VOU1BFQ0lGSUVEEAASCAoET1BFThABEhAKDEFDS05PV0xFREdFRBACEgwKCFJFU09MVkVEEAMSDQoJVElNRURfT1VUEAQy3AEKEUVzY2FsYXRpb25TZXJ2aWNlElUKCEVzY2FsYXRlEiMucm91dGVpcS52MS5jb250cm9sLkVzY2FsYXRlUmVxdWVzdBokLnJvdXRlaXEudjEuY29udHJvbC5Fc2NhbGF0ZVJlc3BvbnNlEnAKEVJlc29sdmVFc2NhbGF0aW9uEiwucm91dGVpcS52MS5jb250cm9sLlJlc29sdmVFc2NhbGF0aW9uUmVxdWVzdBotLnJvdXRlaXEudjEuY29udHJvbC5SZXNvbHZlRXNjYWxhdGlvblJlc3BvbnNlQpUBCjBidWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLmNvbnRyb2xCD0VzY2FsYXRpb25Qcm90b1pQYnVmLmJ1aWxkL2dlbi9nby9zc2ZvcmdlL3JvdXRlaXEvcHJvdG9jb2xidWZmZXJzL2dvL3JvdXRlaXEvdjEvY29udHJvbDtjb250cm9sdjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message routeiq.v1.control.EscalateRequest.
 * Use `create(EscalateRequestSchema)` to create a new message.
 */
export const EscalateRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_escalation, 0);

/**
 * Describes the message routeiq.v1.control.EscalateResponse.
 * Use `create(EscalateResponseSchema)` to create a new message.
 */
export const EscalateResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_escalation, 1);

/**
 * Describes the message routeiq.v1.control.ResolveEscalationRequest.
 * Use `create(ResolveEscalationRequestSchema)` to create a new message.
 */
export const ResolveEscalationRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_escalation, 2);

/**
 * Describes the message routeiq.v1.control.ResolveEscalationResponse.
 * Use `create(ResolveEscalationResponseSchema)` to create a new message.
 */
export const ResolveEscalationResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_escalation, 3);

/**
 * Describes the enum routeiq.v1.control.EscalationUrgency.
 */
export const EscalationUrgencySchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_control_escalation, 0);

/**
 * @generated from enum routeiq.v1.control.EscalationUrgency
 */
export const EscalationUrgency = /*@__PURE__*/
  tsEnum(EscalationUrgencySchema);

/**
 * Describes the enum routeiq.v1.control.EscalationState.
 */
export const EscalationStateSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_control_escalation, 1);

/**
 * @generated from enum routeiq.v1.control.EscalationState
 */
export const EscalationState = /*@__PURE__*/
  tsEnum(EscalationStateSchema);

/**
 * @generated from service routeiq.v1.control.EscalationService
 */
export const EscalationService = /*@__PURE__*/
  serviceDesc(file_routeiq_v1_control_escalation, 0);

