// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/escalation.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/control/escalation.proto.
 */
export declare const file_routeiq_v1_control_escalation: GenFile;

/**
 * @generated from message routeiq.v1.control.EscalateRequest
 */
export declare type EscalateRequest = Message<"routeiq.v1.control.EscalateRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: string context_summary = 3;
   */
  contextSummary: string;

  /**
   * @generated from field: routeiq.v1.control.EscalationUrgency urgency = 4;
   */
  urgency: EscalationUrgency;
};

/**
 * Describes the message routeiq.v1.control.EscalateRequest.
 * Use `create(EscalateRequestSchema)` to create a new message.
 */
export declare const EscalateRequestSchema: GenMessage<EscalateRequest>;

/**
 * @generated from message routeiq.v1.control.EscalateResponse
 */
export declare type EscalateResponse = Message<"routeiq.v1.control.EscalateResponse"> & {
  /**
   * @generated from field: string escalation_id = 1;
   */
  escalationId: string;

  /**
   * @generated from field: routeiq.v1.control.EscalationState state = 2;
   */
  state: EscalationState;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.control.EscalateResponse.
 * Use `create(EscalateResponseSchema)` to create a new message.
 */
export declare const EscalateResponseSchema: GenMessage<EscalateResponse>;

/**
 * @generated from message routeiq.v1.control.ResolveEscalationRequest
 */
export declare type ResolveEscalationRequest = Message<"routeiq.v1.control.ResolveEscalationRequest"> & {
  /**
   * @generated from field: string escalation_id = 1;
   */
  escalationId: string;

  /**
   * @generated from field: string resolution = 2;
   */
  resolution: string;

  /**
   * @generated from field: bool approved = 3;
   */
  approved: boolean;
};

/**
 * Describes the message routeiq.v1.control.ResolveEscalationRequest.
 * Use `create(ResolveEscalationRequestSchema)` to create a new message.
 */
export declare const ResolveEscalationRequestSchema: GenMessage<ResolveEscalationRequest>;

/**
 * @generated from message routeiq.v1.control.ResolveEscalationResponse
 */
export declare type ResolveEscalationResponse = Message<"routeiq.v1.control.ResolveEscalationResponse"> & {
  /**
   * @generated from field: bool accepted = 1;
   */
  accepted: boolean;
};

/**
 * Describes the message routeiq.v1.control.ResolveEscalationResponse.
 * Use `create(ResolveEscalationResponseSchema)` to create a new message.
 */
export declare const ResolveEscalationResponseSchema: GenMessage<ResolveEscalationResponse>;

/**
 * @generated from enum routeiq.v1.control.EscalationUrgency
 */
export enum EscalationUrgency {
  /**
   * @generated from enum value: ESCALATION_URGENCY_UNSPECIFIED = 0;
   */
  ESCALATION_URGENCY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOW = 1;
   */
  LOW = 1,

  /**
   * @generated from enum value: MEDIUM = 2;
   */
  MEDIUM = 2,

  /**
   * @generated from enum value: HIGH = 3;
   */
  HIGH = 3,

  /**
   * @generated from enum value: CRITICAL = 4;
   */
  CRITICAL = 4,
}

/**
 * Describes the enum routeiq.v1.control.EscalationUrgency.
 */
export declare const EscalationUrgencySchema: GenEnum<EscalationUrgency>;

/**
 * @generated from enum routeiq.v1.control.EscalationState
 */
export enum EscalationState {
  /**
   * @generated from enum value: ESCALATION_STATE_UNSPECIFIED = 0;
   */
  ESCALATION_STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: OPEN = 1;
   */
  OPEN = 1,

  /**
   * @generated from enum value: ACKNOWLEDGED = 2;
   */
  ACKNOWLEDGED = 2,

  /**
   * @generated from enum value: RESOLVED = 3;
   */
  RESOLVED = 3,

  /**
   * @generated from enum value: TIMED_OUT = 4;
   */
  TIMED_OUT = 4,
}

/**
 * Describes the enum routeiq.v1.control.EscalationState.
 */
export declare const EscalationStateSchema: GenEnum<EscalationState>;

/**
 * @generated from service routeiq.v1.control.EscalationService
 */
export declare const EscalationService: GenService<{
  /**
   * @generated from rpc routeiq.v1.control.EscalationService.Escalate
   */
  escalate: {
    methodKind: "unary";
    input: typeof EscalateRequestSchema;
    output: typeof EscalateResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.control.EscalationService.ResolveEscalation
   */
  resolveEscalation: {
    methodKind: "unary";
    input: typeof ResolveEscalationRequestSchema;
    output: typeof ResolveEscalationResponseSchema;
  },
}>;

