// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/escalation.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EscalateRequest, EscalateResponse, ResolveEscalationRequest, ResolveEscalationResponse } from "./escalation_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.EscalationService
 */
export const EscalationService = {
  typeName: "routeiq.v1.control.EscalationService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.control.EscalationService.Escalate
     */
    escalate: {
      name: "Escalate",
      I: EscalateRequest,
      O: EscalateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.EscalationService.ResolveEscalation
     */
    resolveEscalation: {
      name: "ResolveEscalation",
      I: ResolveEscalationRequest,
      O: ResolveEscalationResponse,
      kind: MethodKind.Unary,
    },
  }
};

