// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/guardrail.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckGuardrailRequest, CheckGuardrailResponse, RegisterPolicyRequest, RegisterPolicyResponse } from "./guardrail_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.GuardrailService
 */
export declare const GuardrailService: {
  readonly typeName: "routeiq.v1.control.GuardrailService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.control.GuardrailService.CheckGuardrail
     */
    readonly checkGuardrail: {
      readonly name: "CheckGuardrail",
      readonly I: typeof CheckGuardrailRequest,
      readonly O: typeof CheckGuardrailResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.GuardrailService.RegisterPolicy
     */
    readonly registerPolicy: {
      readonly name: "RegisterPolicy",
      readonly I: typeof RegisterPolicyRequest,
      readonly O: typeof RegisterPolicyResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

