// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/guardrail.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckGuardrailRequest, CheckGuardrailResponse, RegisterPolicyRequest, RegisterPolicyResponse } from "./guardrail_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.GuardrailService
 */
export const GuardrailService = {
  typeName: "routeiq.v1.control.GuardrailService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.control.GuardrailService.CheckGuardrail
     */
    checkGuardrail: {
      name: "CheckGuardrail",
      I: CheckGuardrailRequest,
      O: CheckGuardrailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.GuardrailService.RegisterPolicy
     */
    registerPolicy: {
      name: "RegisterPolicy",
      I: RegisterPolicyRequest,
      O: RegisterPolicyResponse,
      kind: MethodKind.Unary,
    },
  }
};

