// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/guardrail.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_routeiq_v1_telemetry_entities } from "../telemetry/entities_pb";

/**
 * Describes the file routeiq/v1/control/guardrail.proto.
 */
export const file_routeiq_v1_control_guardrail = /*@__PURE__*/
  fileDesc("CiJyb3V0ZWlxL3YxL2NvbnRyb2wvZ3VhcmRyYWlsLnByb3RvEhJyb3V0ZWlxLnYxLmNvbnRyb2wimwEKFUNoZWNrR3VhcmRyYWlsUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEhcKD3Byb3Bvc2VkX2FjdGlvbhgCIAEoCRI/ChBwZXJtaXNzaW9uX2xldmVsGAMgASgOMiUucm91dGVpcS52MS50ZWxlbWV0cnkuUGVybWlzc2lvbkxldmVsEhQKDHJpc2tfY29udGV4dBgEIAEoCSJ9ChZDaGVja0d1YXJkcmFpbFJlc3BvbnNlEjUKB3ZlcmRpY3QYASABKA4yJC5yb3V0ZWlxLnYxLmNvbnRyb2wuR3VhcmRyYWlsVmVyZGljdBIOCgZyZWFzb24YAiABKAkSHAoUcG9saWN5X2lkc190cmlnZ2VyZWQYAyADKAkiWgoVUmVnaXN0ZXJQb2xpY3lSZXF1ZXN0EhEKCXBvbGljeV9pZBgBIAEoCRIWCg5idW5kbGVfdmVyc2lvbhgCIAEoCRIWCg5wb2xpY3lfY29udGVudBgDIAEoDCJFChZSZWdpc3RlclBvbGljeVJlc3BvbnNlEhAKCGFjY2VwdGVkGAEgASgIEhkKEWVmZmVjdGl2ZV92ZXJzaW9uGAIgASgJKmEKEEd1YXJkcmFpbFZlcmRpY3QSIQodR1VBUkRSQUlMX1ZFUkRJQ1RfVU5TUEVDSUZJRUQQABIJCgVBTExPVxABEgkKBUJMT0NLEAISFAoQUkVRVUlSRV9BUFBST1ZBTBADMuQBChBHdWFyZHJhaWxTZXJ2aWNlEmcKDkNoZWNrR3VhcmRyYWlsEikucm91dGVpcS52MS5jb250cm9sLkNoZWNrR3VhcmRyYWlsUmVxdWVzdBoqLnJvdXRlaXEudjEuY29udHJvbC5DaGVja0d1YXJkcmFpbFJlc3BvbnNlEmcKDlJlZ2lzdGVyUG9saWN5Eikucm91dGVpcS52MS5jb250cm9sLlJlZ2lzdGVyUG9saWN5UmVxdWVzdBoqLnJvdXRlaXEudjEuY29udHJvbC5SZWdpc3RlclBvbGljeVJlc3BvbnNlQpQBCjBidWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLmNvbnRyb2xCDkd1YXJkcmFpbFByb3RvWlBidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9jb250cm9sO2NvbnRyb2x2MWIGcHJvdG8z", [file_routeiq_v1_telemetry_entities]);

/**
 * Describes the message routeiq.v1.control.CheckGuardrailRequest.
 * Use `create(CheckGuardrailRequestSchema)` to create a new message.
 */
export const CheckGuardrailRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_guardrail, 0);

/**
 * Describes the message routeiq.v1.control.CheckGuardrailResponse.
 * Use `create(CheckGuardrailResponseSchema)` to create a new message.
 */
export const CheckGuardrailResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_guardrail, 1);

/**
 * Describes the message routeiq.v1.control.RegisterPolicyRequest.
 * Use `create(RegisterPolicyRequestSchema)` to create a new message.
 */
export const RegisterPolicyRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_guardrail, 2);

/**
 * Describes the message routeiq.v1.control.RegisterPolicyResponse.
 * Use `create(RegisterPolicyResponseSchema)` to create a new message.
 */
export const RegisterPolicyResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_guardrail, 3);

/**
 * Describes the enum routeiq.v1.control.GuardrailVerdict.
 */
export const GuardrailVerdictSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_control_guardrail, 0);

/**
 * @generated from enum routeiq.v1.control.GuardrailVerdict
 */
export const GuardrailVerdict = /*@__PURE__*/
  tsEnum(GuardrailVerdictSchema);

/**
 * @generated from service routeiq.v1.control.GuardrailService
 */
export const GuardrailService = /*@__PURE__*/
  serviceDesc(file_routeiq_v1_control_guardrail, 0);

