// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/guardrail.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { PermissionLevel } from "../telemetry/entities_pb";

/**
 * Describes the file routeiq/v1/control/guardrail.proto.
 */
export declare const file_routeiq_v1_control_guardrail: GenFile;

/**
 * @generated from message routeiq.v1.control.CheckGuardrailRequest
 */
export declare type CheckGuardrailRequest = Message<"routeiq.v1.control.CheckGuardrailRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string proposed_action = 2;
   */
  proposedAction: string;

  /**
   * @generated from field: routeiq.v1.telemetry.PermissionLevel permission_level = 3;
   */
  permissionLevel: PermissionLevel;

  /**
   * @generated from field: string risk_context = 4;
   */
  riskContext: string;
};

/**
 * Describes the message routeiq.v1.control.CheckGuardrailRequest.
 * Use `create(CheckGuardrailRequestSchema)` to create a new message.
 */
export declare const CheckGuardrailRequestSchema: GenMessage<CheckGuardrailRequest>;

/**
 * @generated from message routeiq.v1.control.CheckGuardrailResponse
 */
export declare type CheckGuardrailResponse = Message<"routeiq.v1.control.CheckGuardrailResponse"> & {
  /**
   * @generated from field: routeiq.v1.control.GuardrailVerdict verdict = 1;
   */
  verdict: GuardrailVerdict;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: repeated string policy_ids_triggered = 3;
   */
  policyIdsTriggered: string[];
};

/**
 * Describes the message routeiq.v1.control.CheckGuardrailResponse.
 * Use `create(CheckGuardrailResponseSchema)` to create a new message.
 */
export declare const CheckGuardrailResponseSchema: GenMessage<CheckGuardrailResponse>;

/**
 * @generated from message routeiq.v1.control.RegisterPolicyRequest
 */
export declare type RegisterPolicyRequest = Message<"routeiq.v1.control.RegisterPolicyRequest"> & {
  /**
   * @generated from field: string policy_id = 1;
   */
  policyId: string;

  /**
   * @generated from field: string bundle_version = 2;
   */
  bundleVersion: string;

  /**
   * @generated from field: bytes policy_content = 3;
   */
  policyContent: Uint8Array;
};

/**
 * Describes the message routeiq.v1.control.RegisterPolicyRequest.
 * Use `create(RegisterPolicyRequestSchema)` to create a new message.
 */
export declare const RegisterPolicyRequestSchema: GenMessage<RegisterPolicyRequest>;

/**
 * @generated from message routeiq.v1.control.RegisterPolicyResponse
 */
export declare type RegisterPolicyResponse = Message<"routeiq.v1.control.RegisterPolicyResponse"> & {
  /**
   * @generated from field: bool accepted = 1;
   */
  accepted: boolean;

  /**
   * @generated from field: string effective_version = 2;
   */
  effectiveVersion: string;
};

/**
 * Describes the message routeiq.v1.control.RegisterPolicyResponse.
 * Use `create(RegisterPolicyResponseSchema)` to create a new message.
 */
export declare const RegisterPolicyResponseSchema: GenMessage<RegisterPolicyResponse>;

/**
 * @generated from enum routeiq.v1.control.GuardrailVerdict
 */
export enum GuardrailVerdict {
  /**
   * @generated from enum value: GUARDRAIL_VERDICT_UNSPECIFIED = 0;
   */
  GUARDRAIL_VERDICT_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ALLOW = 1;
   */
  ALLOW = 1,

  /**
   * @generated from enum value: BLOCK = 2;
   */
  BLOCK = 2,

  /**
   * @generated from enum value: REQUIRE_APPROVAL = 3;
   */
  REQUIRE_APPROVAL = 3,
}

/**
 * Describes the enum routeiq.v1.control.GuardrailVerdict.
 */
export declare const GuardrailVerdictSchema: GenEnum<GuardrailVerdict>;

/**
 * @generated from service routeiq.v1.control.GuardrailService
 */
export declare const GuardrailService: GenService<{
  /**
   * @generated from rpc routeiq.v1.control.GuardrailService.CheckGuardrail
   */
  checkGuardrail: {
    methodKind: "unary";
    input: typeof CheckGuardrailRequestSchema;
    output: typeof CheckGuardrailResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.control.GuardrailService.RegisterPolicy
   */
  registerPolicy: {
    methodKind: "unary";
    input: typeof RegisterPolicyRequestSchema;
    output: typeof RegisterPolicyResponseSchema;
  },
}>;

