// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/intervention.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AutonomyMode } from "../telemetry/entities_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/control/intervention.proto.
 */
export declare const file_routeiq_v1_control_intervention: GenFile;

/**
 * @generated from message routeiq.v1.control.TriggerInterventionRequest
 */
export declare type TriggerInterventionRequest = Message<"routeiq.v1.control.TriggerInterventionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: routeiq.v1.control.InterventionKind kind = 2;
   */
  kind: InterventionKind;

  /**
   * @generated from field: string reason = 3;
   */
  reason: string;

  /**
   * @generated from field: routeiq.v1.telemetry.AutonomyMode downgrade_to = 4;
   */
  downgradeTo: AutonomyMode;
};

/**
 * Describes the message routeiq.v1.control.TriggerInterventionRequest.
 * Use `create(TriggerInterventionRequestSchema)` to create a new message.
 */
export declare const TriggerInterventionRequestSchema: GenMessage<TriggerInterventionRequest>;

/**
 * @generated from message routeiq.v1.control.TriggerInterventionResponse
 */
export declare type TriggerInterventionResponse = Message<"routeiq.v1.control.TriggerInterventionResponse"> & {
  /**
   * @generated from field: string intervention_id = 1;
   */
  interventionId: string;

  /**
   * @generated from field: bool applied = 2;
   */
  applied: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp applied_at = 3;
   */
  appliedAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.control.TriggerInterventionResponse.
 * Use `create(TriggerInterventionResponseSchema)` to create a new message.
 */
export declare const TriggerInterventionResponseSchema: GenMessage<TriggerInterventionResponse>;

/**
 * @generated from message routeiq.v1.control.GetInterventionStatusRequest
 */
export declare type GetInterventionStatusRequest = Message<"routeiq.v1.control.GetInterventionStatusRequest"> & {
  /**
   * @generated from field: string intervention_id = 1;
   */
  interventionId: string;
};

/**
 * Describes the message routeiq.v1.control.GetInterventionStatusRequest.
 * Use `create(GetInterventionStatusRequestSchema)` to create a new message.
 */
export declare const GetInterventionStatusRequestSchema: GenMessage<GetInterventionStatusRequest>;

/**
 * @generated from message routeiq.v1.control.GetInterventionStatusResponse
 */
export declare type GetInterventionStatusResponse = Message<"routeiq.v1.control.GetInterventionStatusResponse"> & {
  /**
   * @generated from field: string intervention_id = 1;
   */
  interventionId: string;

  /**
   * @generated from field: routeiq.v1.control.InterventionKind kind = 2;
   */
  kind: InterventionKind;

  /**
   * @generated from field: bool active = 3;
   */
  active: boolean;
};

/**
 * Describes the message routeiq.v1.control.GetInterventionStatusResponse.
 * Use `create(GetInterventionStatusResponseSchema)` to create a new message.
 */
export declare const GetInterventionStatusResponseSchema: GenMessage<GetInterventionStatusResponse>;

/**
 * @generated from enum routeiq.v1.control.InterventionKind
 */
export enum InterventionKind {
  /**
   * @generated from enum value: INTERVENTION_KIND_UNSPECIFIED = 0;
   */
  INTERVENTION_KIND_UNSPECIFIED = 0,

  /**
   * @generated from enum value: CIRCUIT_BREAK = 1;
   */
  CIRCUIT_BREAK = 1,

  /**
   * @generated from enum value: ROLLBACK = 2;
   */
  ROLLBACK = 2,

  /**
   * @generated from enum value: AUTONOMY_DOWNGRADE = 3;
   */
  AUTONOMY_DOWNGRADE = 3,

  /**
   * @generated from enum value: MODEL_SWAP = 4;
   */
  MODEL_SWAP = 4,

  /**
   * @generated from enum value: HARD_STOP = 5;
   */
  HARD_STOP = 5,
}

/**
 * Describes the enum routeiq.v1.control.InterventionKind.
 */
export declare const InterventionKindSchema: GenEnum<InterventionKind>;

/**
 * @generated from service routeiq.v1.control.InterventionService
 */
export declare const InterventionService: GenService<{
  /**
   * @generated from rpc routeiq.v1.control.InterventionService.TriggerIntervention
   */
  triggerIntervention: {
    methodKind: "unary";
    input: typeof TriggerInterventionRequestSchema;
    output: typeof TriggerInterventionResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.control.InterventionService.GetInterventionStatus
   */
  getInterventionStatus: {
    methodKind: "unary";
    input: typeof GetInterventionStatusRequestSchema;
    output: typeof GetInterventionStatusResponseSchema;
  },
}>;

