// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/intervention.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetInterventionStatusRequest, GetInterventionStatusResponse, TriggerInterventionRequest, TriggerInterventionResponse } from "./intervention_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.InterventionService
 */
export const InterventionService = {
  typeName: "routeiq.v1.control.InterventionService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.control.InterventionService.TriggerIntervention
     */
    triggerIntervention: {
      name: "TriggerIntervention",
      I: TriggerInterventionRequest,
      O: TriggerInterventionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.InterventionService.GetInterventionStatus
     */
    getInterventionStatus: {
      name: "GetInterventionStatus",
      I: GetInterventionStatusRequest,
      O: GetInterventionStatusResponse,
      kind: MethodKind.Unary,
    },
  }
};

