// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/intervention.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetInterventionStatusRequest, GetInterventionStatusResponse, TriggerInterventionRequest, TriggerInterventionResponse } from "./intervention_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.InterventionService
 */
export declare const InterventionService: {
  readonly typeName: "routeiq.v1.control.InterventionService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.control.InterventionService.TriggerIntervention
     */
    readonly triggerIntervention: {
      readonly name: "TriggerIntervention",
      readonly I: typeof TriggerInterventionRequest,
      readonly O: typeof TriggerInterventionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.InterventionService.GetInterventionStatus
     */
    readonly getInterventionStatus: {
      readonly name: "GetInterventionStatus",
      readonly I: typeof GetInterventionStatusRequest,
      readonly O: typeof GetInterventionStatusResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

