// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/intervention.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_routeiq_v1_telemetry_entities } from "../telemetry/entities_pb";

/**
 * Describes the file routeiq/v1/control/intervention.proto.
 */
export const file_routeiq_v1_control_intervention = /*@__PURE__*/
  fileDesc("CiVyb3V0ZWlxL3YxL2NvbnRyb2wvaW50ZXJ2ZW50aW9uLnByb3RvEhJyb3V0ZWlxLnYxLmNvbnRyb2wirgEKGlRyaWdnZXJJbnRlcnZlbnRpb25SZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSMgoEa2luZBgCIAEoDjIkLnJvdXRlaXEudjEuY29udHJvbC5JbnRlcnZlbnRpb25LaW5kEg4KBnJlYXNvbhgDIAEoCRI4Cgxkb3duZ3JhZGVfdG8YBCABKA4yIi5yb3V0ZWlxLnYxLnRlbGVtZXRyeS5BdXRvbm9teU1vZGUidwobVHJpZ2dlckludGVydmVudGlvblJlc3BvbnNlEhcKD2ludGVydmVudGlvbl9pZBgBIAEoCRIPCgdhcHBsaWVkGAIgASgIEi4KCmFwcGxpZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIjcKHEdldEludGVydmVudGlvblN0YXR1c1JlcXVlc3QSFwoPaW50ZXJ2ZW50aW9uX2lkGAEgASgJInwKHUdldEludGVydmVudGlvblN0YXR1c1Jlc3BvbnNlEhcKD2ludGVydmVudGlvbl9pZBgBIAEoCRIyCgRraW5kGAIgASgOMiQucm91dGVpcS52MS5jb250cm9sLkludGVydmVudGlvbktpbmQSDgoGYWN0aXZlGAMgASgIKo0BChBJbnRlcnZlbnRpb25LaW5kEiEKHUlOVEVSVkVOVElPTl9LSU5EX1VOU1BFQ0lGSUVEEAASEQoNQ0lSQ1VJVF9CUkVBSxABEgwKCFJPTExCQUNLEAISFgoSQVVUT05PTVlfRE9XTkdSQURFEAMSDgoKTU9ERUxfU1dBUBAEEg0KCUhBUkRfU1RPUBAFMosCChNJbnRlcnZlbnRpb25TZXJ2aWNlEnYKE1RyaWdnZXJJbnRlcnZlbnRpb24SLi5yb3V0ZWlxLnYxLmNvbnRyb2wuVHJpZ2dlckludGVydmVudGlvblJlcXVlc3QaLy5yb3V0ZWlxLnYxLmNvbnRyb2wuVHJpZ2dlckludGVydmVudGlvblJlc3BvbnNlEnwKFUdldEludGVydmVudGlvblN0YXR1cxIwLnJvdXRlaXEudjEuY29udHJvbC5HZXRJbnRlcnZlbnRpb25TdGF0dXNSZXF1ZXN0GjEucm91dGVpcS52MS5jb250cm9sLkdldEludGVydmVudGlvblN0YXR1c1Jlc3BvbnNlQpcBCjBidWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLmNvbnRyb2xCEUludGVydmVudGlvblByb3RvWlBidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9jb250cm9sO2NvbnRyb2x2MWIGcHJvdG8z", [file_google_protobuf_timestamp, file_routeiq_v1_telemetry_entities]);

/**
 * Describes the message routeiq.v1.control.TriggerInterventionRequest.
 * Use `create(TriggerInterventionRequestSchema)` to create a new message.
 */
export const TriggerInterventionRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_intervention, 0);

/**
 * Describes the message routeiq.v1.control.TriggerInterventionResponse.
 * Use `create(TriggerInterventionResponseSchema)` to create a new message.
 */
export const TriggerInterventionResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_intervention, 1);

/**
 * Describes the message routeiq.v1.control.GetInterventionStatusRequest.
 * Use `create(GetInterventionStatusRequestSchema)` to create a new message.
 */
export const GetInterventionStatusRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_intervention, 2);

/**
 * Describes the message routeiq.v1.control.GetInterventionStatusResponse.
 * Use `create(GetInterventionStatusResponseSchema)` to create a new message.
 */
export const GetInterventionStatusResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_intervention, 3);

/**
 * Describes the enum routeiq.v1.control.InterventionKind.
 */
export const InterventionKindSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_control_intervention, 0);

/**
 * @generated from enum routeiq.v1.control.InterventionKind
 */
export const InterventionKind = /*@__PURE__*/
  tsEnum(InterventionKindSchema);

/**
 * @generated from service routeiq.v1.control.InterventionService
 */
export const InterventionService = /*@__PURE__*/
  serviceDesc(file_routeiq_v1_control_intervention, 0);

