// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/session.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EndSessionRequest, EndSessionResponse, StartSessionRequest, StartSessionResponse, UpdateStateRequest, UpdateStateResponse } from "./session_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.SessionService
 */
export declare const SessionService: {
  readonly typeName: "routeiq.v1.control.SessionService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.control.SessionService.StartSession
     */
    readonly startSession: {
      readonly name: "StartSession",
      readonly I: typeof StartSessionRequest,
      readonly O: typeof StartSessionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.SessionService.EndSession
     */
    readonly endSession: {
      readonly name: "EndSession",
      readonly I: typeof EndSessionRequest,
      readonly O: typeof EndSessionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.SessionService.UpdateState
     */
    readonly updateState: {
      readonly name: "UpdateState",
      readonly I: typeof UpdateStateRequest,
      readonly O: typeof UpdateStateResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

