// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/control/session.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EndSessionRequest, EndSessionResponse, StartSessionRequest, StartSessionResponse, UpdateStateRequest, UpdateStateResponse } from "./session_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.control.SessionService
 */
export const SessionService = {
  typeName: "routeiq.v1.control.SessionService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.control.SessionService.StartSession
     */
    startSession: {
      name: "StartSession",
      I: StartSessionRequest,
      O: StartSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.SessionService.EndSession
     */
    endSession: {
      name: "EndSession",
      I: EndSessionRequest,
      O: EndSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.control.SessionService.UpdateState
     */
    updateState: {
      name: "UpdateState",
      I: UpdateStateRequest,
      O: UpdateStateResponse,
      kind: MethodKind.Unary,
    },
  }
};

