// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/session.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_routeiq_v1_telemetry_entities } from "../telemetry/entities_pb";

/**
 * Describes the file routeiq/v1/control/session.proto.
 */
export const file_routeiq_v1_control_session = /*@__PURE__*/
  fileDesc("CiByb3V0ZWlxL3YxL2NvbnRyb2wvc2Vzc2lvbi5wcm90bxIScm91dGVpcS52MS5jb250cm9sIs4BChNTdGFydFNlc3Npb25SZXF1ZXN0Eg8KB3Rhc2tfaWQYASABKAkSEAoIYWdlbnRfaWQYAiABKAkSEQoJdGVuYW50X2lkGAMgASgJEhMKC2Vudmlyb25tZW50GAQgASgJEjkKDWF1dG9ub215X21vZGUYBSABKA4yIi5yb3V0ZWlxLnYxLnRlbGVtZXRyeS5BdXRvbm9teU1vZGUSMQoJcmlza190aWVyGAYgASgOMh4ucm91dGVpcS52MS50ZWxlbWV0cnkuUmlza1RpZXIiWgoUU3RhcnRTZXNzaW9uUmVzcG9uc2USEgoKc2Vzc2lvbl9pZBgBIAEoCRIuCgpzdGFydGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJqChFFbmRTZXNzaW9uUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEkEKEWNvbXBsZXRpb25fc3RhdHVzGAIgASgOMiYucm91dGVpcS52MS50ZWxlbWV0cnkuQ29tcGxldGlvblN0YXR1cyImChJFbmRTZXNzaW9uUmVzcG9uc2USEAoIYWNjZXB0ZWQYASABKAgiUAoSVXBkYXRlU3RhdGVSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSEQoJc3RhdGVfa2V5GAIgASgJEhMKC3N0YXRlX3ZhbHVlGAMgASgMIj4KE1VwZGF0ZVN0YXRlUmVzcG9uc2USEAoIYWNjZXB0ZWQYASABKAgSFQoNc3RhdGVfdmVyc2lvbhgCIAEoCTKwAgoOU2Vzc2lvblNlcnZpY2USYQoMU3RhcnRTZXNzaW9uEicucm91dGVpcS52MS5jb250cm9sLlN0YXJ0U2Vzc2lvblJlcXVlc3QaKC5yb3V0ZWlxLnYxLmNvbnRyb2wuU3RhcnRTZXNzaW9uUmVzcG9uc2USWwoKRW5kU2Vzc2lvbhIlLnJvdXRlaXEudjEuY29udHJvbC5FbmRTZXNzaW9uUmVxdWVzdBomLnJvdXRlaXEudjEuY29udHJvbC5FbmRTZXNzaW9uUmVzcG9uc2USXgoLVXBkYXRlU3RhdGUSJi5yb3V0ZWlxLnYxLmNvbnRyb2wuVXBkYXRlU3RhdGVSZXF1ZXN0Gicucm91dGVpcS52MS5jb250cm9sLlVwZGF0ZVN0YXRlUmVzcG9uc2VCkgEKMGJ1aWxkLmJ1Zi5nZW4uc3Nmb3JnZS5yb3V0ZWlxLnJvdXRlaXEudjEuY29udHJvbEIMU2Vzc2lvblByb3RvWlBidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9jb250cm9sO2NvbnRyb2x2MWIGcHJvdG8z", [file_google_protobuf_timestamp, file_routeiq_v1_telemetry_entities]);

/**
 * Describes the message routeiq.v1.control.StartSessionRequest.
 * Use `create(StartSessionRequestSchema)` to create a new message.
 */
export const StartSessionRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_session, 0);

/**
 * Describes the message routeiq.v1.control.StartSessionResponse.
 * Use `create(StartSessionResponseSchema)` to create a new message.
 */
export const StartSessionResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_session, 1);

/**
 * Describes the message routeiq.v1.control.EndSessionRequest.
 * Use `create(EndSessionRequestSchema)` to create a new message.
 */
export const EndSessionRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_session, 2);

/**
 * Describes the message routeiq.v1.control.EndSessionResponse.
 * Use `create(EndSessionResponseSchema)` to create a new message.
 */
export const EndSessionResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_session, 3);

/**
 * Describes the message routeiq.v1.control.UpdateStateRequest.
 * Use `create(UpdateStateRequestSchema)` to create a new message.
 */
export const UpdateStateRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_session, 4);

/**
 * Describes the message routeiq.v1.control.UpdateStateResponse.
 * Use `create(UpdateStateResponseSchema)` to create a new message.
 */
export const UpdateStateResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_control_session, 5);

/**
 * @generated from service routeiq.v1.control.SessionService
 */
export const SessionService = /*@__PURE__*/
  serviceDesc(file_routeiq_v1_control_session, 0);

