// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/control/session.proto (package routeiq.v1.control, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AutonomyMode, CompletionStatus, RiskTier } from "../telemetry/entities_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/control/session.proto.
 */
export declare const file_routeiq_v1_control_session: GenFile;

/**
 * @generated from message routeiq.v1.control.StartSessionRequest
 */
export declare type StartSessionRequest = Message<"routeiq.v1.control.StartSessionRequest"> & {
  /**
   * @generated from field: string task_id = 1;
   */
  taskId: string;

  /**
   * @generated from field: string agent_id = 2;
   */
  agentId: string;

  /**
   * @generated from field: string tenant_id = 3;
   */
  tenantId: string;

  /**
   * @generated from field: string environment = 4;
   */
  environment: string;

  /**
   * @generated from field: routeiq.v1.telemetry.AutonomyMode autonomy_mode = 5;
   */
  autonomyMode: AutonomyMode;

  /**
   * @generated from field: routeiq.v1.telemetry.RiskTier risk_tier = 6;
   */
  riskTier: RiskTier;
};

/**
 * Describes the message routeiq.v1.control.StartSessionRequest.
 * Use `create(StartSessionRequestSchema)` to create a new message.
 */
export declare const StartSessionRequestSchema: GenMessage<StartSessionRequest>;

/**
 * @generated from message routeiq.v1.control.StartSessionResponse
 */
export declare type StartSessionResponse = Message<"routeiq.v1.control.StartSessionResponse"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 2;
   */
  startedAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.control.StartSessionResponse.
 * Use `create(StartSessionResponseSchema)` to create a new message.
 */
export declare const StartSessionResponseSchema: GenMessage<StartSessionResponse>;

/**
 * @generated from message routeiq.v1.control.EndSessionRequest
 */
export declare type EndSessionRequest = Message<"routeiq.v1.control.EndSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: routeiq.v1.telemetry.CompletionStatus completion_status = 2;
   */
  completionStatus: CompletionStatus;
};

/**
 * Describes the message routeiq.v1.control.EndSessionRequest.
 * Use `create(EndSessionRequestSchema)` to create a new message.
 */
export declare const EndSessionRequestSchema: GenMessage<EndSessionRequest>;

/**
 * @generated from message routeiq.v1.control.EndSessionResponse
 */
export declare type EndSessionResponse = Message<"routeiq.v1.control.EndSessionResponse"> & {
  /**
   * @generated from field: bool accepted = 1;
   */
  accepted: boolean;
};

/**
 * Describes the message routeiq.v1.control.EndSessionResponse.
 * Use `create(EndSessionResponseSchema)` to create a new message.
 */
export declare const EndSessionResponseSchema: GenMessage<EndSessionResponse>;

/**
 * @generated from message routeiq.v1.control.UpdateStateRequest
 */
export declare type UpdateStateRequest = Message<"routeiq.v1.control.UpdateStateRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string state_key = 2;
   */
  stateKey: string;

  /**
   * @generated from field: bytes state_value = 3;
   */
  stateValue: Uint8Array;
};

/**
 * Describes the message routeiq.v1.control.UpdateStateRequest.
 * Use `create(UpdateStateRequestSchema)` to create a new message.
 */
export declare const UpdateStateRequestSchema: GenMessage<UpdateStateRequest>;

/**
 * @generated from message routeiq.v1.control.UpdateStateResponse
 */
export declare type UpdateStateResponse = Message<"routeiq.v1.control.UpdateStateResponse"> & {
  /**
   * @generated from field: bool accepted = 1;
   */
  accepted: boolean;

  /**
   * @generated from field: string state_version = 2;
   */
  stateVersion: string;
};

/**
 * Describes the message routeiq.v1.control.UpdateStateResponse.
 * Use `create(UpdateStateResponseSchema)` to create a new message.
 */
export declare const UpdateStateResponseSchema: GenMessage<UpdateStateResponse>;

/**
 * @generated from service routeiq.v1.control.SessionService
 */
export declare const SessionService: GenService<{
  /**
   * @generated from rpc routeiq.v1.control.SessionService.StartSession
   */
  startSession: {
    methodKind: "unary";
    input: typeof StartSessionRequestSchema;
    output: typeof StartSessionResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.control.SessionService.EndSession
   */
  endSession: {
    methodKind: "unary";
    input: typeof EndSessionRequestSchema;
    output: typeof EndSessionResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.control.SessionService.UpdateState
   */
  updateState: {
    methodKind: "unary";
    input: typeof UpdateStateRequestSchema;
    output: typeof UpdateStateResponseSchema;
  },
}>;

