// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/telemetry/conventions.proto (package routeiq.v1.telemetry, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AttributeType } from "./entities_pb";

/**
 * Describes the file routeiq/v1/telemetry/conventions.proto.
 */
export declare const file_routeiq_v1_telemetry_conventions: GenFile;

/**
 * SemanticConvention maps a typed proto field to its OTel span attribute key.
 * Read by the SDK code generator to emit the right attribute keys.
 * Read by routeiq_validator (collector component) to validate incoming spans.
 *
 * @generated from message routeiq.v1.telemetry.SemanticConvention
 */
export declare type SemanticConvention = Message<"routeiq.v1.telemetry.SemanticConvention"> & {
  /**
   * e.g. "TaskEvent.completion_status"
   *
   * @generated from field: string proto_field_path = 1;
   */
  protoFieldPath: string;

  /**
   * e.g. "routeiq.task.completion_status"
   *
   * @generated from field: string otel_attribute_key = 2;
   */
  otelAttributeKey: string;

  /**
   * @generated from field: routeiq.v1.telemetry.AttributeType type = 3;
   */
  type: AttributeType;

  /**
   * @generated from field: bool required = 4;
   */
  required: boolean;
};

/**
 * Describes the message routeiq.v1.telemetry.SemanticConvention.
 * Use `create(SemanticConventionSchema)` to create a new message.
 */
export declare const SemanticConventionSchema: GenMessage<SemanticConvention>;

/**
 * ConventionRegistry is the root message for conventions/telemetry.yaml.
 * Every AgentEvent field that appears on the wire must have an entry here.
 *
 * @generated from message routeiq.v1.telemetry.ConventionRegistry
 */
export declare type ConventionRegistry = Message<"routeiq.v1.telemetry.ConventionRegistry"> & {
  /**
   * @generated from field: repeated routeiq.v1.telemetry.SemanticConvention conventions = 1;
   */
  conventions: SemanticConvention[];
};

/**
 * Describes the message routeiq.v1.telemetry.ConventionRegistry.
 * Use `create(ConventionRegistrySchema)` to create a new message.
 */
export declare const ConventionRegistrySchema: GenMessage<ConventionRegistry>;

