// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/telemetry/conventions.proto (package routeiq.v1.telemetry, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_routeiq_v1_telemetry_entities } from "./entities_pb";

/**
 * Describes the file routeiq/v1/telemetry/conventions.proto.
 */
export const file_routeiq_v1_telemetry_conventions = /*@__PURE__*/
  fileDesc("CiZyb3V0ZWlxL3YxL3RlbGVtZXRyeS9jb252ZW50aW9ucy5wcm90bxIUcm91dGVpcS52MS50ZWxlbWV0cnkijwEKElNlbWFudGljQ29udmVudGlvbhIYChBwcm90b19maWVsZF9wYXRoGAEgASgJEhoKEm90ZWxfYXR0cmlidXRlX2tleRgCIAEoCRIxCgR0eXBlGAMgASgOMiMucm91dGVpcS52MS50ZWxlbWV0cnkuQXR0cmlidXRlVHlwZRIQCghyZXF1aXJlZBgEIAEoCCJTChJDb252ZW50aW9uUmVnaXN0cnkSPQoLY29udmVudGlvbnMYASADKAsyKC5yb3V0ZWlxLnYxLnRlbGVtZXRyeS5TZW1hbnRpY0NvbnZlbnRpb25CnAEKMmJ1aWxkLmJ1Zi5nZW4uc3Nmb3JnZS5yb3V0ZWlxLnJvdXRlaXEudjEudGVsZW1ldHJ5QhBDb252ZW50aW9uc1Byb3RvWlRidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS90ZWxlbWV0cnk7dGVsZW1ldHJ5djFiBnByb3RvMw", [file_routeiq_v1_telemetry_entities]);

/**
 * Describes the message routeiq.v1.telemetry.SemanticConvention.
 * Use `create(SemanticConventionSchema)` to create a new message.
 */
export const SemanticConventionSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_telemetry_conventions, 0);

/**
 * Describes the message routeiq.v1.telemetry.ConventionRegistry.
 * Use `create(ConventionRegistrySchema)` to create a new message.
 */
export const ConventionRegistrySchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_telemetry_conventions, 1);

