// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/telemetry/entities.proto (package routeiq.v1.telemetry, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file routeiq/v1/telemetry/entities.proto.
 */
export const file_routeiq_v1_telemetry_entities = /*@__PURE__*/
  fileDesc("CiNyb3V0ZWlxL3YxL3RlbGVtZXRyeS9lbnRpdGllcy5wcm90bxIUcm91dGVpcS52MS50ZWxlbWV0cnkqeAoQQ29tcGxldGlvblN0YXR1cxIhCh1DT01QTEVUSU9OX1NUQVRVU19VTlNQRUNJRklFRBAAEgsKB1NVQ0NFU1MQARILCgdGQUlMVVJFEAISCwoHUEFSVElBTBADEg0KCUNBTkNFTExFRBAEEgsKB1RJTUVPVVQQBSrSAQoPRmFpbHVyZUNhdGVnb3J5EiAKHEZBSUxVUkVfQ0FURUdPUllfVU5TUEVDSUZJRUQQABIOCgpUT09MX0VSUk9SEAESDwoLTU9ERUxfRVJST1IQAhIQCgxQT0xJQ1lfQkxPQ0sQAxIRCg1MT09QX0RFVEVDVEVEEAQSFAoQVElNRU9VVF9FWENFRURFRBAFEhMKD0hVTUFOX0NBTkNFTExFRBAGEhYKElJFU09VUkNFX0VYSEFVU1RFRBAHEhQKEENPTlRFWFRfT1ZFUkZMT1cQCCpiCgxBdXRvbm9teU1vZGUSHQoZQVVUT05PTVlfTU9ERV9VTlNQRUNJRklFRBAAEg4KClNVUEVSVklTRUQQARITCg9TRU1JX0FVVE9OT01PVVMQAhIOCgpBVVRPTk9NT1VTEAMqUgoIUmlza1RpZXISGQoVUklTS19USUVSX1VOU1BFQ0lGSUVEEAASBwoDTE9XEAESCgoGTUVESVVNEAISCAoESElHSBADEgwKCENSSVRJQ0FMEAQqbgoPUGVybWlzc2lvbkxldmVsEiAKHFBFUk1JU1NJT05fTEVWRUxfVU5TUEVDSUZJRUQQABINCglSRUFEX09OTFkQARIOCgpSRUFEX1dSSVRFEAISDgoKUFJJVklMRUdFRBADEgoKBlNZU1RFTRAEKogBChBUb29sUmVzdWx0U3RhdHVzEiIKHlRPT0xfUkVTVUxUX1NUQVRVU19VTlNQRUNJRklFRBAAEhAKDFRPT0xfU1VDQ0VTUxABEhAKDFRPT0xfRkFJTFVSRRACEhAKDFRPT0xfVElNRU9VVBADEhoKFlRPT0xfUEVSTUlTU0lPTl9ERU5JRUQQBCp5Cg1BdHRyaWJ1dGVUeXBlEh4KGkFUVFJJQlVURV9UWVBFX1VOU1BFQ0lGSUVEEAASCgoGU1RSSU5HEAESCQoFSU5UNjQQAhIKCgZET1VCTEUQAxIICgRCT09MEAQSCQoFQllURVMQBRIQCgxTVFJJTkdfQVJSQVkQBkKZAQoyYnVpbGQuYnVmLmdlbi5zc2ZvcmdlLnJvdXRlaXEucm91dGVpcS52MS50ZWxlbWV0cnlCDUVudGl0aWVzUHJvdG9aVGJ1Zi5idWlsZC9nZW4vZ28vc3Nmb3JnZS9yb3V0ZWlxL3Byb3RvY29sYnVmZmVycy9nby9yb3V0ZWlxL3YxL3RlbGVtZXRyeTt0ZWxlbWV0cnl2MWIGcHJvdG8z");

/**
 * Describes the enum routeiq.v1.telemetry.CompletionStatus.
 */
export const CompletionStatusSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_telemetry_entities, 0);

/**
 * @generated from enum routeiq.v1.telemetry.CompletionStatus
 */
export const CompletionStatus = /*@__PURE__*/
  tsEnum(CompletionStatusSchema);

/**
 * Describes the enum routeiq.v1.telemetry.FailureCategory.
 */
export const FailureCategorySchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_telemetry_entities, 1);

/**
 * @generated from enum routeiq.v1.telemetry.FailureCategory
 */
export const FailureCategory = /*@__PURE__*/
  tsEnum(FailureCategorySchema);

/**
 * Describes the enum routeiq.v1.telemetry.AutonomyMode.
 */
export const AutonomyModeSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_telemetry_entities, 2);

/**
 * @generated from enum routeiq.v1.telemetry.AutonomyMode
 */
export const AutonomyMode = /*@__PURE__*/
  tsEnum(AutonomyModeSchema);

/**
 * Describes the enum routeiq.v1.telemetry.RiskTier.
 */
export const RiskTierSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_telemetry_entities, 3);

/**
 * @generated from enum routeiq.v1.telemetry.RiskTier
 */
export const RiskTier = /*@__PURE__*/
  tsEnum(RiskTierSchema);

/**
 * Describes the enum routeiq.v1.telemetry.PermissionLevel.
 */
export const PermissionLevelSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_telemetry_entities, 4);

/**
 * @generated from enum routeiq.v1.telemetry.PermissionLevel
 */
export const PermissionLevel = /*@__PURE__*/
  tsEnum(PermissionLevelSchema);

/**
 * Describes the enum routeiq.v1.telemetry.ToolResultStatus.
 */
export const ToolResultStatusSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_telemetry_entities, 5);

/**
 * @generated from enum routeiq.v1.telemetry.ToolResultStatus
 */
export const ToolResultStatus = /*@__PURE__*/
  tsEnum(ToolResultStatusSchema);

/**
 * Describes the enum routeiq.v1.telemetry.AttributeType.
 */
export const AttributeTypeSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_telemetry_entities, 6);

/**
 * @generated from enum routeiq.v1.telemetry.AttributeType
 */
export const AttributeType = /*@__PURE__*/
  tsEnum(AttributeTypeSchema);

