// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/telemetry/entities.proto (package routeiq.v1.telemetry, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file routeiq/v1/telemetry/entities.proto.
 */
export declare const file_routeiq_v1_telemetry_entities: GenFile;

/**
 * @generated from enum routeiq.v1.telemetry.CompletionStatus
 */
export enum CompletionStatus {
  /**
   * @generated from enum value: COMPLETION_STATUS_UNSPECIFIED = 0;
   */
  COMPLETION_STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SUCCESS = 1;
   */
  SUCCESS = 1,

  /**
   * @generated from enum value: FAILURE = 2;
   */
  FAILURE = 2,

  /**
   * @generated from enum value: PARTIAL = 3;
   */
  PARTIAL = 3,

  /**
   * @generated from enum value: CANCELLED = 4;
   */
  CANCELLED = 4,

  /**
   * @generated from enum value: TIMEOUT = 5;
   */
  TIMEOUT = 5,
}

/**
 * Describes the enum routeiq.v1.telemetry.CompletionStatus.
 */
export declare const CompletionStatusSchema: GenEnum<CompletionStatus>;

/**
 * @generated from enum routeiq.v1.telemetry.FailureCategory
 */
export enum FailureCategory {
  /**
   * @generated from enum value: FAILURE_CATEGORY_UNSPECIFIED = 0;
   */
  FAILURE_CATEGORY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: TOOL_ERROR = 1;
   */
  TOOL_ERROR = 1,

  /**
   * @generated from enum value: MODEL_ERROR = 2;
   */
  MODEL_ERROR = 2,

  /**
   * @generated from enum value: POLICY_BLOCK = 3;
   */
  POLICY_BLOCK = 3,

  /**
   * @generated from enum value: LOOP_DETECTED = 4;
   */
  LOOP_DETECTED = 4,

  /**
   * @generated from enum value: TIMEOUT_EXCEEDED = 5;
   */
  TIMEOUT_EXCEEDED = 5,

  /**
   * @generated from enum value: HUMAN_CANCELLED = 6;
   */
  HUMAN_CANCELLED = 6,

  /**
   * @generated from enum value: RESOURCE_EXHAUSTED = 7;
   */
  RESOURCE_EXHAUSTED = 7,

  /**
   * @generated from enum value: CONTEXT_OVERFLOW = 8;
   */
  CONTEXT_OVERFLOW = 8,
}

/**
 * Describes the enum routeiq.v1.telemetry.FailureCategory.
 */
export declare const FailureCategorySchema: GenEnum<FailureCategory>;

/**
 * @generated from enum routeiq.v1.telemetry.AutonomyMode
 */
export enum AutonomyMode {
  /**
   * @generated from enum value: AUTONOMY_MODE_UNSPECIFIED = 0;
   */
  AUTONOMY_MODE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SUPERVISED = 1;
   */
  SUPERVISED = 1,

  /**
   * @generated from enum value: SEMI_AUTONOMOUS = 2;
   */
  SEMI_AUTONOMOUS = 2,

  /**
   * @generated from enum value: AUTONOMOUS = 3;
   */
  AUTONOMOUS = 3,
}

/**
 * Describes the enum routeiq.v1.telemetry.AutonomyMode.
 */
export declare const AutonomyModeSchema: GenEnum<AutonomyMode>;

/**
 * @generated from enum routeiq.v1.telemetry.RiskTier
 */
export enum RiskTier {
  /**
   * @generated from enum value: RISK_TIER_UNSPECIFIED = 0;
   */
  RISK_TIER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOW = 1;
   */
  LOW = 1,

  /**
   * @generated from enum value: MEDIUM = 2;
   */
  MEDIUM = 2,

  /**
   * @generated from enum value: HIGH = 3;
   */
  HIGH = 3,

  /**
   * @generated from enum value: CRITICAL = 4;
   */
  CRITICAL = 4,
}

/**
 * Describes the enum routeiq.v1.telemetry.RiskTier.
 */
export declare const RiskTierSchema: GenEnum<RiskTier>;

/**
 * @generated from enum routeiq.v1.telemetry.PermissionLevel
 */
export enum PermissionLevel {
  /**
   * @generated from enum value: PERMISSION_LEVEL_UNSPECIFIED = 0;
   */
  PERMISSION_LEVEL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: READ_ONLY = 1;
   */
  READ_ONLY = 1,

  /**
   * @generated from enum value: READ_WRITE = 2;
   */
  READ_WRITE = 2,

  /**
   * @generated from enum value: PRIVILEGED = 3;
   */
  PRIVILEGED = 3,

  /**
   * @generated from enum value: SYSTEM = 4;
   */
  SYSTEM = 4,
}

/**
 * Describes the enum routeiq.v1.telemetry.PermissionLevel.
 */
export declare const PermissionLevelSchema: GenEnum<PermissionLevel>;

/**
 * @generated from enum routeiq.v1.telemetry.ToolResultStatus
 */
export enum ToolResultStatus {
  /**
   * @generated from enum value: TOOL_RESULT_STATUS_UNSPECIFIED = 0;
   */
  TOOL_RESULT_STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: TOOL_SUCCESS = 1;
   */
  TOOL_SUCCESS = 1,

  /**
   * @generated from enum value: TOOL_FAILURE = 2;
   */
  TOOL_FAILURE = 2,

  /**
   * @generated from enum value: TOOL_TIMEOUT = 3;
   */
  TOOL_TIMEOUT = 3,

  /**
   * @generated from enum value: TOOL_PERMISSION_DENIED = 4;
   */
  TOOL_PERMISSION_DENIED = 4,
}

/**
 * Describes the enum routeiq.v1.telemetry.ToolResultStatus.
 */
export declare const ToolResultStatusSchema: GenEnum<ToolResultStatus>;

/**
 * @generated from enum routeiq.v1.telemetry.AttributeType
 */
export enum AttributeType {
  /**
   * @generated from enum value: ATTRIBUTE_TYPE_UNSPECIFIED = 0;
   */
  ATTRIBUTE_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: STRING = 1;
   */
  STRING = 1,

  /**
   * @generated from enum value: INT64 = 2;
   */
  INT64 = 2,

  /**
   * @generated from enum value: DOUBLE = 3;
   */
  DOUBLE = 3,

  /**
   * @generated from enum value: BOOL = 4;
   */
  BOOL = 4,

  /**
   * @generated from enum value: BYTES = 5;
   */
  BYTES = 5,

  /**
   * @generated from enum value: STRING_ARRAY = 6;
   */
  STRING_ARRAY = 6,
}

/**
 * Describes the enum routeiq.v1.telemetry.AttributeType.
 */
export declare const AttributeTypeSchema: GenEnum<AttributeType>;

