// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/telemetry/events.proto (package routeiq.v1.telemetry, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { AutonomyMode, CompletionStatus, FailureCategory, PermissionLevel, RiskTier, ToolResultStatus } from "./entities_pb";

/**
 * Describes the file routeiq/v1/telemetry/events.proto.
 */
export declare const file_routeiq_v1_telemetry_events: GenFile;

/**
 * VersionLineage carries the full software bill-of-materials for a run.
 *
 * @generated from message routeiq.v1.telemetry.VersionLineage
 */
export declare type VersionLineage = Message<"routeiq.v1.telemetry.VersionLineage"> & {
  /**
   * @generated from field: string agent_version = 1;
   */
  agentVersion: string;

  /**
   * @generated from field: string model_name = 2;
   */
  modelName: string;

  /**
   * @generated from field: string model_version = 3;
   */
  modelVersion: string;

  /**
   * @generated from field: string prompt_version = 4;
   */
  promptVersion: string;

  /**
   * @generated from field: string toolchain_version = 5;
   */
  toolchainVersion: string;

  /**
   * @generated from field: string memory_version = 6;
   */
  memoryVersion: string;

  /**
   * @generated from field: string retrieval_version = 7;
   */
  retrievalVersion: string;

  /**
   * @generated from field: string policy_bundle_version = 8;
   */
  policyBundleVersion: string;
};

/**
 * Describes the message routeiq.v1.telemetry.VersionLineage.
 * Use `create(VersionLineageSchema)` to create a new message.
 */
export declare const VersionLineageSchema: GenMessage<VersionLineage>;

/**
 * AgentEvent is the canonical envelope for every event emitted by an agent.
 * Maps to an OTel span with routeiq.* attributes (see conventions/telemetry.yaml).
 *
 * @generated from message routeiq.v1.telemetry.AgentEvent
 */
export declare type AgentEvent = Message<"routeiq.v1.telemetry.AgentEvent"> & {
  /**
   * @generated from field: bytes trace_id = 1;
   */
  traceId: Uint8Array;

  /**
   * @generated from field: bytes span_id = 2;
   */
  spanId: Uint8Array;

  /**
   * @generated from field: bytes parent_span_id = 3;
   */
  parentSpanId: Uint8Array;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from field: routeiq.v1.telemetry.EventType event_type = 5;
   */
  eventType: EventType;

  /**
   * @generated from field: string tenant_id = 6;
   */
  tenantId: string;

  /**
   * @generated from field: string environment = 7;
   */
  environment: string;

  /**
   * @generated from field: string task_id = 8;
   */
  taskId: string;

  /**
   * @generated from field: string run_id = 9;
   */
  runId: string;

  /**
   * @generated from field: string step_id = 10;
   */
  stepId: string;

  /**
   * @generated from field: string agent_id = 11;
   */
  agentId: string;

  /**
   * @generated from field: string agent_role = 12;
   */
  agentRole: string;

  /**
   * @generated from field: string workflow_id = 13;
   */
  workflowId: string;

  /**
   * @generated from field: routeiq.v1.telemetry.VersionLineage versions = 14;
   */
  versions?: VersionLineage | undefined;

  /**
   * @generated from field: routeiq.v1.telemetry.AutonomyMode autonomy_mode = 15;
   */
  autonomyMode: AutonomyMode;

  /**
   * @generated from field: routeiq.v1.telemetry.RiskTier risk_tier = 16;
   */
  riskTier: RiskTier;

  /**
   * @generated from oneof routeiq.v1.telemetry.AgentEvent.payload
   */
  payload: {
    /**
     * @generated from field: routeiq.v1.telemetry.TaskEvent task = 100;
     */
    value: TaskEvent;
    case: "task";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.StepEvent step = 101;
     */
    value: StepEvent;
    case: "step";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.DecisionEvent decision = 102;
     */
    value: DecisionEvent;
    case: "decision";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.ToolCallEvent tool_call = 103;
     */
    value: ToolCallEvent;
    case: "toolCall";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.RetrievalEvent retrieval = 104;
     */
    value: RetrievalEvent;
    case: "retrieval";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.MemoryEvent memory = 105;
     */
    value: MemoryEvent;
    case: "memory";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.HandoffEvent handoff = 106;
     */
    value: HandoffEvent;
    case: "handoff";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.PolicyEvent policy = 107;
     */
    value: PolicyEvent;
    case: "policy";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.InterventionEvent intervention = 108;
     */
    value: InterventionEvent;
    case: "intervention";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.RecoveryEvent recovery = 109;
     */
    value: RecoveryEvent;
    case: "recovery";
  } | {
    /**
     * @generated from field: routeiq.v1.telemetry.StateSnapshotEvent state_snapshot = 110;
     */
    value: StateSnapshotEvent;
    case: "stateSnapshot";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message routeiq.v1.telemetry.AgentEvent.
 * Use `create(AgentEventSchema)` to create a new message.
 */
export declare const AgentEventSchema: GenMessage<AgentEvent>;

/**
 * TaskEvent carries the outcome of a complete agent task.
 *
 * @generated from message routeiq.v1.telemetry.TaskEvent
 */
export declare type TaskEvent = Message<"routeiq.v1.telemetry.TaskEvent"> & {
  /**
   * @generated from field: string input_intent = 1;
   */
  inputIntent: string;

  /**
   * @generated from field: string normalized_task_type = 2;
   */
  normalizedTaskType: string;

  /**
   * @generated from field: string expected_outcome = 3;
   */
  expectedOutcome: string;

  /**
   * @generated from field: string actual_outcome = 4;
   */
  actualOutcome: string;

  /**
   * @generated from field: routeiq.v1.telemetry.CompletionStatus completion_status = 5;
   */
  completionStatus: CompletionStatus;

  /**
   * @generated from field: routeiq.v1.telemetry.FailureCategory failure_category = 6;
   */
  failureCategory: FailureCategory;

  /**
   * @generated from field: double total_cost_usd = 7;
   */
  totalCostUsd: number;

  /**
   * @generated from field: int64 total_tokens = 8;
   */
  totalTokens: bigint;

  /**
   * @generated from field: bool human_escalated = 9;
   */
  humanEscalated: boolean;

  /**
   * @generated from field: bool rolled_back = 10;
   */
  rolledBack: boolean;

  /**
   * @generated from field: string cohort = 11;
   */
  cohort: string;
};

/**
 * Describes the message routeiq.v1.telemetry.TaskEvent.
 * Use `create(TaskEventSchema)` to create a new message.
 */
export declare const TaskEventSchema: GenMessage<TaskEvent>;

/**
 * ToolCallEvent records a single tool invocation within a step.
 *
 * @generated from message routeiq.v1.telemetry.ToolCallEvent
 */
export declare type ToolCallEvent = Message<"routeiq.v1.telemetry.ToolCallEvent"> & {
  /**
   * @generated from field: string tool_name = 1;
   */
  toolName: string;

  /**
   * @generated from field: string tool_version = 2;
   */
  toolVersion: string;

  /**
   * @generated from field: string arguments_hash = 3;
   */
  argumentsHash: string;

  /**
   * @generated from field: string arguments_summary = 4;
   */
  argumentsSummary: string;

  /**
   * @generated from field: routeiq.v1.telemetry.PermissionLevel permission_level = 5;
   */
  permissionLevel: PermissionLevel;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 6;
   */
  startTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 7;
   */
  endTime?: Timestamp | undefined;

  /**
   * @generated from field: double latency_ms = 8;
   */
  latencyMs: number;

  /**
   * @generated from field: routeiq.v1.telemetry.ToolResultStatus result_status = 9;
   */
  resultStatus: ToolResultStatus;

  /**
   * @generated from field: string error_code = 10;
   */
  errorCode: string;

  /**
   * @generated from field: string result_summary = 11;
   */
  resultSummary: string;

  /**
   * @generated from field: repeated string result_quality_flags = 12;
   */
  resultQualityFlags: string[];
};

/**
 * Describes the message routeiq.v1.telemetry.ToolCallEvent.
 * Use `create(ToolCallEventSchema)` to create a new message.
 */
export declare const ToolCallEventSchema: GenMessage<ToolCallEvent>;

/**
 * StepEvent captures the outcome of a single reasoning step within a task run.
 *
 * @generated from message routeiq.v1.telemetry.StepEvent
 */
export declare type StepEvent = Message<"routeiq.v1.telemetry.StepEvent"> & {
  /**
   * @generated from field: string selected_action = 1;
   */
  selectedAction: string;

  /**
   * @generated from field: string action_rationale = 2;
   */
  actionRationale: string;

  /**
   * @generated from field: routeiq.v1.telemetry.CompletionStatus completion_status = 3;
   */
  completionStatus: CompletionStatus;

  /**
   * @generated from field: routeiq.v1.telemetry.FailureCategory failure_category = 4;
   */
  failureCategory: FailureCategory;

  /**
   * @generated from field: int32 step_index = 5;
   */
  stepIndex: number;

  /**
   * @generated from field: int32 retry_count = 6;
   */
  retryCount: number;
};

/**
 * Describes the message routeiq.v1.telemetry.StepEvent.
 * Use `create(StepEventSchema)` to create a new message.
 */
export declare const StepEventSchema: GenMessage<StepEvent>;

/**
 * DecisionEvent records a branching decision point — which path or tool the agent chose.
 *
 * @generated from message routeiq.v1.telemetry.DecisionEvent
 */
export declare type DecisionEvent = Message<"routeiq.v1.telemetry.DecisionEvent"> & {
  /**
   * "tool_selection" | "path_choice" | "escalation_check"
   *
   * @generated from field: string decision_type = 1;
   */
  decisionType: string;

  /**
   * JSON or natural-language summary of alternatives
   *
   * @generated from field: string options_considered = 2;
   */
  optionsConsidered: string;

  /**
   * @generated from field: string chosen_option = 3;
   */
  chosenOption: string;

  /**
   * @generated from field: string rationale = 4;
   */
  rationale: string;

  /**
   * 0.0–1.0 model-reported confidence
   *
   * @generated from field: double confidence = 5;
   */
  confidence: number;
};

/**
 * Describes the message routeiq.v1.telemetry.DecisionEvent.
 * Use `create(DecisionEventSchema)` to create a new message.
 */
export declare const DecisionEventSchema: GenMessage<DecisionEvent>;

/**
 * RetrievalEvent records a RAG, search, or knowledge-base lookup.
 *
 * @generated from message routeiq.v1.telemetry.RetrievalEvent
 */
export declare type RetrievalEvent = Message<"routeiq.v1.telemetry.RetrievalEvent"> & {
  /**
   * "vector" | "keyword" | "hybrid" | "graph"
   *
   * @generated from field: string retrieval_type = 1;
   */
  retrievalType: string;

  /**
   * sanitized query — PII redacted by collector
   *
   * @generated from field: string query_summary = 2;
   */
  querySummary: string;

  /**
   * @generated from field: int32 results_count = 3;
   */
  resultsCount: number;

  /**
   * @generated from field: double top_score = 4;
   */
  topScore: number;

  /**
   * true if result was served from cache
   *
   * @generated from field: bool cache_hit = 5;
   */
  cacheHit: boolean;

  /**
   * @generated from field: double latency_ms = 6;
   */
  latencyMs: number;
};

/**
 * Describes the message routeiq.v1.telemetry.RetrievalEvent.
 * Use `create(RetrievalEventSchema)` to create a new message.
 */
export declare const RetrievalEventSchema: GenMessage<RetrievalEvent>;

/**
 * MemoryEvent records a read or write to the agent's memory store.
 *
 * @generated from message routeiq.v1.telemetry.MemoryEvent
 */
export declare type MemoryEvent = Message<"routeiq.v1.telemetry.MemoryEvent"> & {
  /**
   * "short_term" | "long_term" | "episodic" | "semantic"
   *
   * @generated from field: string memory_type = 1;
   */
  memoryType: string;

  /**
   * "read" | "write" | "delete" | "search"
   *
   * @generated from field: string operation = 2;
   */
  operation: string;

  /**
   * sanitized key/description — PII redacted by collector
   *
   * @generated from field: string key_summary = 3;
   */
  keySummary: string;

  /**
   * @generated from field: int32 entries_affected = 4;
   */
  entriesAffected: number;
};

/**
 * Describes the message routeiq.v1.telemetry.MemoryEvent.
 * Use `create(MemoryEventSchema)` to create a new message.
 */
export declare const MemoryEventSchema: GenMessage<MemoryEvent>;

/**
 * HandoffEvent records an agent-to-agent delegation of a task or sub-task.
 *
 * @generated from message routeiq.v1.telemetry.HandoffEvent
 */
export declare type HandoffEvent = Message<"routeiq.v1.telemetry.HandoffEvent"> & {
  /**
   * @generated from field: string from_agent_id = 1;
   */
  fromAgentId: string;

  /**
   * @generated from field: string to_agent_id = 2;
   */
  toAgentId: string;

  /**
   * @generated from field: string handoff_reason = 3;
   */
  handoffReason: string;

  /**
   * COMPLETED = handoff accepted; FAILURE = rejected
   *
   * @generated from field: routeiq.v1.telemetry.CompletionStatus status = 4;
   */
  status: CompletionStatus;

  /**
   * sanitized summary of context passed to receiving agent
   *
   * @generated from field: string context_summary = 5;
   */
  contextSummary: string;
};

/**
 * Describes the message routeiq.v1.telemetry.HandoffEvent.
 * Use `create(HandoffEventSchema)` to create a new message.
 */
export declare const HandoffEventSchema: GenMessage<HandoffEvent>;

/**
 * PolicyEvent records the evaluation of a policy bundle against a proposed action.
 *
 * @generated from message routeiq.v1.telemetry.PolicyEvent
 */
export declare type PolicyEvent = Message<"routeiq.v1.telemetry.PolicyEvent"> & {
  /**
   * @generated from field: string policy_id = 1;
   */
  policyId: string;

  /**
   * @generated from field: string bundle_version = 2;
   */
  bundleVersion: string;

  /**
   * @generated from field: string action_evaluated = 3;
   */
  actionEvaluated: string;

  /**
   * "allow" | "block" | "require_approval"
   *
   * @generated from field: string verdict = 4;
   */
  verdict: string;

  /**
   * IDs of individual rules that fired
   *
   * @generated from field: repeated string rules_triggered = 5;
   */
  rulesTriggered: string[];
};

/**
 * Describes the message routeiq.v1.telemetry.PolicyEvent.
 * Use `create(PolicyEventSchema)` to create a new message.
 */
export declare const PolicyEventSchema: GenMessage<PolicyEvent>;

/**
 * InterventionEvent records a system or human intervention that interrupted normal agent flow.
 *
 * @generated from message routeiq.v1.telemetry.InterventionEvent
 */
export declare type InterventionEvent = Message<"routeiq.v1.telemetry.InterventionEvent"> & {
  /**
   * "circuit_break" | "rollback" | "escalate_human" | "model_swap" | "autonomy_downgrade"
   *
   * @generated from field: string intervention_type = 1;
   */
  interventionType: string;

  /**
   * @generated from field: string trigger_reason = 2;
   */
  triggerReason: string;

  /**
   * metric that breached threshold, if system-triggered
   *
   * @generated from field: string trigger_metric_id = 3;
   */
  triggerMetricId: string;

  /**
   * true = system-triggered; false = human-triggered
   *
   * @generated from field: bool automated = 4;
   */
  automated: boolean;
};

/**
 * Describes the message routeiq.v1.telemetry.InterventionEvent.
 * Use `create(InterventionEventSchema)` to create a new message.
 */
export declare const InterventionEventSchema: GenMessage<InterventionEvent>;

/**
 * RecoveryEvent records a recovery attempt following a failure or intervention.
 *
 * @generated from message routeiq.v1.telemetry.RecoveryEvent
 */
export declare type RecoveryEvent = Message<"routeiq.v1.telemetry.RecoveryEvent"> & {
  /**
   * "retry" | "fallback" | "rollback" | "restart"
   *
   * @generated from field: string recovery_type = 1;
   */
  recoveryType: string;

  /**
   * error code or short description of what failed
   *
   * @generated from field: string from_error = 2;
   */
  fromError: string;

  /**
   * @generated from field: bool succeeded = 3;
   */
  succeeded: boolean;

  /**
   * 1-indexed; >1 means this is a retry
   *
   * @generated from field: int32 attempt_number = 4;
   */
  attemptNumber: number;
};

/**
 * Describes the message routeiq.v1.telemetry.RecoveryEvent.
 * Use `create(RecoveryEventSchema)` to create a new message.
 */
export declare const RecoveryEventSchema: GenMessage<RecoveryEvent>;

/**
 * StateSnapshotEvent records a point-in-time capture of agent working state.
 *
 * @generated from message routeiq.v1.telemetry.StateSnapshotEvent
 */
export declare type StateSnapshotEvent = Message<"routeiq.v1.telemetry.StateSnapshotEvent"> & {
  /**
   * "checkpoint" | "pre_tool" | "post_tool" | "on_error"
   *
   * @generated from field: string snapshot_type = 1;
   */
  snapshotType: string;

  /**
   * @generated from field: int64 state_size_bytes = 2;
   */
  stateSizeBytes: bigint;

  /**
   * @generated from field: string snapshot_id = 3;
   */
  snapshotId: string;
};

/**
 * Describes the message routeiq.v1.telemetry.StateSnapshotEvent.
 * Use `create(StateSnapshotEventSchema)` to create a new message.
 */
export declare const StateSnapshotEventSchema: GenMessage<StateSnapshotEvent>;

/**
 * @generated from enum routeiq.v1.telemetry.EventType
 */
export enum EventType {
  /**
   * @generated from enum value: EVENT_TYPE_UNSPECIFIED = 0;
   */
  EVENT_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: TASK_STARTED = 1;
   */
  TASK_STARTED = 1,

  /**
   * @generated from enum value: TASK_COMPLETED = 2;
   */
  TASK_COMPLETED = 2,

  /**
   * @generated from enum value: TASK_FAILED = 3;
   */
  TASK_FAILED = 3,

  /**
   * @generated from enum value: STEP_STARTED = 4;
   */
  STEP_STARTED = 4,

  /**
   * @generated from enum value: STEP_COMPLETED = 5;
   */
  STEP_COMPLETED = 5,

  /**
   * @generated from enum value: DECISION_MADE = 6;
   */
  DECISION_MADE = 6,

  /**
   * @generated from enum value: TOOL_CALLED = 7;
   */
  TOOL_CALLED = 7,

  /**
   * @generated from enum value: TOOL_RETURNED = 8;
   */
  TOOL_RETURNED = 8,

  /**
   * @generated from enum value: RETRIEVAL_PERFORMED = 9;
   */
  RETRIEVAL_PERFORMED = 9,

  /**
   * @generated from enum value: MEMORY_READ = 10;
   */
  MEMORY_READ = 10,

  /**
   * @generated from enum value: MEMORY_WRITTEN = 11;
   */
  MEMORY_WRITTEN = 11,

  /**
   * @generated from enum value: HANDOFF_INITIATED = 12;
   */
  HANDOFF_INITIATED = 12,

  /**
   * @generated from enum value: HANDOFF_ACCEPTED = 13;
   */
  HANDOFF_ACCEPTED = 13,

  /**
   * @generated from enum value: POLICY_EVALUATED = 14;
   */
  POLICY_EVALUATED = 14,

  /**
   * @generated from enum value: INTERVENTION_TRIGGERED = 15;
   */
  INTERVENTION_TRIGGERED = 15,

  /**
   * @generated from enum value: RECOVERY_ATTEMPTED = 16;
   */
  RECOVERY_ATTEMPTED = 16,

  /**
   * @generated from enum value: STATE_SNAPSHOT_CAPTURED = 17;
   */
  STATE_SNAPSHOT_CAPTURED = 17,
}

/**
 * Describes the enum routeiq.v1.telemetry.EventType.
 */
export declare const EventTypeSchema: GenEnum<EventType>;

