// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/metrics/definitions.proto (package routeiq.v1.metrics, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EventType } from "../telemetry/events_pb";

/**
 * Describes the file routeiq/v1/metrics/definitions.proto.
 */
export declare const file_routeiq_v1_metrics_definitions: GenFile;

/**
 * MetricDefinition is the canonical declaration of a single derived metric.
 * Lives in routeiq-catalog as YAML; this proto defines the shape only.
 *
 * @generated from message routeiq.v1.metrics.MetricDefinition
 */
export declare type MetricDefinition = Message<"routeiq.v1.metrics.MetricDefinition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: routeiq.v1.metrics.Layer layer = 4;
   */
  layer: Layer;

  /**
   * @generated from field: routeiq.v1.metrics.EvidenceClass evidence_class = 5;
   */
  evidenceClass: EvidenceClass;

  /**
   * @generated from field: repeated routeiq.v1.metrics.MetricInput inputs = 6;
   */
  inputs: MetricInput[];

  /**
   * @generated from field: routeiq.v1.metrics.Formula formula = 7;
   */
  formula?: Formula | undefined;

  /**
   * @generated from field: string unit = 8;
   */
  unit: string;

  /**
   * @generated from field: routeiq.v1.metrics.Aggregation default_aggregation = 9;
   */
  defaultAggregation: Aggregation;

  /**
   * @generated from field: repeated routeiq.v1.metrics.SloTemplate slo_templates = 10;
   */
  sloTemplates: SloTemplate[];
};

/**
 * Describes the message routeiq.v1.metrics.MetricDefinition.
 * Use `create(MetricDefinitionSchema)` to create a new message.
 */
export declare const MetricDefinitionSchema: GenMessage<MetricDefinition>;

/**
 * @generated from message routeiq.v1.metrics.MetricInput
 */
export declare type MetricInput = Message<"routeiq.v1.metrics.MetricInput"> & {
  /**
   * @generated from field: repeated routeiq.v1.telemetry.EventType event_types = 1;
   */
  eventTypes: EventType[];

  /**
   * @generated from field: repeated string field_paths = 2;
   */
  fieldPaths: string[];

  /**
   * @generated from field: string filter = 3;
   */
  filter: string;
};

/**
 * Describes the message routeiq.v1.metrics.MetricInput.
 * Use `create(MetricInputSchema)` to create a new message.
 */
export declare const MetricInputSchema: GenMessage<MetricInput>;

/**
 * @generated from message routeiq.v1.metrics.SloTemplate
 */
export declare type SloTemplate = Message<"routeiq.v1.metrics.SloTemplate"> & {
  /**
   * @generated from field: string tier = 1;
   */
  tier: string;

  /**
   * @generated from field: string target = 2;
   */
  target: string;
};

/**
 * Describes the message routeiq.v1.metrics.SloTemplate.
 * Use `create(SloTemplateSchema)` to create a new message.
 */
export declare const SloTemplateSchema: GenMessage<SloTemplate>;

/**
 * Formula is the computation declaration for a metric. Exactly one kind is set.
 *
 * @generated from message routeiq.v1.metrics.Formula
 */
export declare type Formula = Message<"routeiq.v1.metrics.Formula"> & {
  /**
   * @generated from oneof routeiq.v1.metrics.Formula.kind
   */
  kind: {
    /**
     * @generated from field: routeiq.v1.metrics.DeterministicFormula deterministic = 1;
     */
    value: DeterministicFormula;
    case: "deterministic";
  } | {
    /**
     * @generated from field: routeiq.v1.metrics.HeuristicFormula heuristic = 2;
     */
    value: HeuristicFormula;
    case: "heuristic";
  } | {
    /**
     * @generated from field: routeiq.v1.metrics.SemanticFormula semantic = 3;
     */
    value: SemanticFormula;
    case: "semantic";
  } | {
    /**
     * @generated from field: routeiq.v1.metrics.FrontierFormula frontier = 4;
     */
    value: FrontierFormula;
    case: "frontier";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message routeiq.v1.metrics.Formula.
 * Use `create(FormulaSchema)` to create a new message.
 */
export declare const FormulaSchema: GenMessage<Formula>;

/**
 * @generated from message routeiq.v1.metrics.DeterministicFormula
 */
export declare type DeterministicFormula = Message<"routeiq.v1.metrics.DeterministicFormula"> & {
  /**
   * @generated from field: string expression = 1;
   */
  expression: string;
};

/**
 * Describes the message routeiq.v1.metrics.DeterministicFormula.
 * Use `create(DeterministicFormulaSchema)` to create a new message.
 */
export declare const DeterministicFormulaSchema: GenMessage<DeterministicFormula>;

/**
 * @generated from message routeiq.v1.metrics.HeuristicFormula
 */
export declare type HeuristicFormula = Message<"routeiq.v1.metrics.HeuristicFormula"> & {
  /**
   * @generated from field: string detector_id = 1;
   */
  detectorId: string;

  /**
   * @generated from field: map<string, string> parameters = 2;
   */
  parameters: { [key: string]: string };
};

/**
 * Describes the message routeiq.v1.metrics.HeuristicFormula.
 * Use `create(HeuristicFormulaSchema)` to create a new message.
 */
export declare const HeuristicFormulaSchema: GenMessage<HeuristicFormula>;

/**
 * @generated from message routeiq.v1.metrics.SemanticFormula
 */
export declare type SemanticFormula = Message<"routeiq.v1.metrics.SemanticFormula"> & {
  /**
   * @generated from field: string classifier_id = 1;
   */
  classifierId: string;

  /**
   * @generated from field: string operation = 2;
   */
  operation: string;
};

/**
 * Describes the message routeiq.v1.metrics.SemanticFormula.
 * Use `create(SemanticFormulaSchema)` to create a new message.
 */
export declare const SemanticFormulaSchema: GenMessage<SemanticFormula>;

/**
 * @generated from message routeiq.v1.metrics.FrontierFormula
 */
export declare type FrontierFormula = Message<"routeiq.v1.metrics.FrontierFormula"> & {
  /**
   * @generated from field: string judge_model = 1;
   */
  judgeModel: string;

  /**
   * @generated from field: string rubric_id = 2;
   */
  rubricId: string;
};

/**
 * Describes the message routeiq.v1.metrics.FrontierFormula.
 * Use `create(FrontierFormulaSchema)` to create a new message.
 */
export declare const FrontierFormulaSchema: GenMessage<FrontierFormula>;

/**
 * @generated from enum routeiq.v1.metrics.Layer
 */
export enum Layer {
  /**
   * @generated from enum value: LAYER_UNSPECIFIED = 0;
   */
  LAYER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LAYER_0_RUNTIME = 1;
   */
  LAYER_0_RUNTIME = 1,

  /**
   * @generated from enum value: LAYER_1_AGENT_BEHAVIOR = 2;
   */
  LAYER_1_AGENT_BEHAVIOR = 2,

  /**
   * @generated from enum value: LAYER_2_QUALITY = 3;
   */
  LAYER_2_QUALITY = 3,

  /**
   * @generated from enum value: LAYER_3_BUSINESS = 4;
   */
  LAYER_3_BUSINESS = 4,

  /**
   * @generated from enum value: LAYER_4_GOVERNANCE = 5;
   */
  LAYER_4_GOVERNANCE = 5,
}

/**
 * Describes the enum routeiq.v1.metrics.Layer.
 */
export declare const LayerSchema: GenEnum<Layer>;

/**
 * @generated from enum routeiq.v1.metrics.EvidenceClass
 */
export enum EvidenceClass {
  /**
   * @generated from enum value: EVIDENCE_UNSPECIFIED = 0;
   */
  EVIDENCE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: OTEL_DIRECT = 1;
   */
  OTEL_DIRECT = 1,

  /**
   * @generated from enum value: HEURISTIC = 2;
   */
  HEURISTIC = 2,

  /**
   * @generated from enum value: SEMANTIC = 3;
   */
  SEMANTIC = 3,

  /**
   * @generated from enum value: FRONTIER = 4;
   */
  FRONTIER = 4,
}

/**
 * Describes the enum routeiq.v1.metrics.EvidenceClass.
 */
export declare const EvidenceClassSchema: GenEnum<EvidenceClass>;

/**
 * @generated from enum routeiq.v1.metrics.Aggregation
 */
export enum Aggregation {
  /**
   * @generated from enum value: AGGREGATION_UNSPECIFIED = 0;
   */
  AGGREGATION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: AVG = 1;
   */
  AVG = 1,

  /**
   * @generated from enum value: SUM = 2;
   */
  SUM = 2,

  /**
   * @generated from enum value: COUNT = 3;
   */
  COUNT = 3,

  /**
   * @generated from enum value: RATE = 4;
   */
  RATE = 4,

  /**
   * @generated from enum value: P50 = 5;
   */
  P50 = 5,

  /**
   * @generated from enum value: P90 = 6;
   */
  P90 = 6,

  /**
   * @generated from enum value: P95 = 7;
   */
  P95 = 7,

  /**
   * @generated from enum value: P99 = 8;
   */
  P99 = 8,

  /**
   * @generated from enum value: MAX = 9;
   */
  MAX = 9,

  /**
   * @generated from enum value: MIN = 10;
   */
  MIN = 10,

  /**
   * @generated from enum value: LAST = 11;
   */
  LAST = 11,
}

/**
 * Describes the enum routeiq.v1.metrics.Aggregation.
 */
export declare const AggregationSchema: GenEnum<Aggregation>;

