// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/billing.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_routeiq_v1_admin_organization } from "./organization_pb";

/**
 * Describes the file routeiq/v1/admin/billing.proto.
 */
export const file_routeiq_v1_admin_billing = /*@__PURE__*/
  fileDesc("Ch5yb3V0ZWlxL3YxL2FkbWluL2JpbGxpbmcucHJvdG8SEHJvdXRlaXEudjEuYWRtaW4i8wEKDFVzYWdlU3VtbWFyeRIXCg9vcmdhbml6YXRpb25faWQYASABKAkSMAoMcGVyaW9kX3N0YXJ0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgpwZXJpb2RfZW5kGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIXCg9ldmVudHNfaW5nZXN0ZWQYBCABKAMSGQoRbWV0cmljc19ldmFsdWF0ZWQYBSABKAMSHAoUZnJvbnRpZXJfanVkZ2VfY2FsbHMYBiABKAMSFgoOdG90YWxfY29zdF91c2QYByABKAEimgEKBVF1b3RhEhcKD29yZ2FuaXphdGlvbl9pZBgBIAEoCRIkCgR0aWVyGAIgASgOMhYucm91dGVpcS52MS5hZG1pbi5UaWVyEhgKEGV2ZW50c19wZXJfbW9udGgYAyABKAMSIAoYZnJvbnRpZXJfY2FsbHNfcGVyX21vbnRoGAQgASgDEhYKDnJldGVudGlvbl9kYXlzGAUgASgDIowBCg9HZXRVc2FnZVJlcXVlc3QSFwoPb3JnYW5pemF0aW9uX2lkGAEgASgJEjAKDHBlcmlvZF9zdGFydBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKcGVyaW9kX2VuZBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiKgoPR2V0UXVvdGFSZXF1ZXN0EhcKD29yZ2FuaXphdGlvbl9pZBgBIAEoCTKnAQoOQmlsbGluZ1NlcnZpY2USTQoIR2V0VXNhZ2USIS5yb3V0ZWlxLnYxLmFkbWluLkdldFVzYWdlUmVxdWVzdBoeLnJvdXRlaXEudjEuYWRtaW4uVXNhZ2VTdW1tYXJ5EkYKCEdldFF1b3RhEiEucm91dGVpcS52MS5hZG1pbi5HZXRRdW90YVJlcXVlc3QaFy5yb3V0ZWlxLnYxLmFkbWluLlF1b3RhQowBCi5idWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLmFkbWluQgxCaWxsaW5nUHJvdG9aTGJ1Zi5idWlsZC9nZW4vZ28vc3Nmb3JnZS9yb3V0ZWlxL3Byb3RvY29sYnVmZmVycy9nby9yb3V0ZWlxL3YxL2FkbWluO2FkbWludjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_routeiq_v1_admin_organization]);

/**
 * Describes the message routeiq.v1.admin.UsageSummary.
 * Use `create(UsageSummarySchema)` to create a new message.
 */
export const UsageSummarySchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_billing, 0);

/**
 * Describes the message routeiq.v1.admin.Quota.
 * Use `create(QuotaSchema)` to create a new message.
 */
export const QuotaSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_billing, 1);

/**
 * Describes the message routeiq.v1.admin.GetUsageRequest.
 * Use `create(GetUsageRequestSchema)` to create a new message.
 */
export const GetUsageRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_billing, 2);

/**
 * Describes the message routeiq.v1.admin.GetQuotaRequest.
 * Use `create(GetQuotaRequestSchema)` to create a new message.
 */
export const GetQuotaRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_billing, 3);

/**
 * @generated from service routeiq.v1.admin.BillingService
 */
export const BillingService = /*@__PURE__*/
  serviceDesc(file_routeiq_v1_admin_billing, 0);

