// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/billing.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { Tier } from "./organization_pb";

/**
 * Describes the file routeiq/v1/admin/billing.proto.
 */
export declare const file_routeiq_v1_admin_billing: GenFile;

/**
 * @generated from message routeiq.v1.admin.UsageSummary
 */
export declare type UsageSummary = Message<"routeiq.v1.admin.UsageSummary"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: google.protobuf.Timestamp period_start = 2;
   */
  periodStart?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp period_end = 3;
   */
  periodEnd?: Timestamp | undefined;

  /**
   * @generated from field: int64 events_ingested = 4;
   */
  eventsIngested: bigint;

  /**
   * @generated from field: int64 metrics_evaluated = 5;
   */
  metricsEvaluated: bigint;

  /**
   * @generated from field: int64 frontier_judge_calls = 6;
   */
  frontierJudgeCalls: bigint;

  /**
   * @generated from field: double total_cost_usd = 7;
   */
  totalCostUsd: number;
};

/**
 * Describes the message routeiq.v1.admin.UsageSummary.
 * Use `create(UsageSummarySchema)` to create a new message.
 */
export declare const UsageSummarySchema: GenMessage<UsageSummary>;

/**
 * @generated from message routeiq.v1.admin.Quota
 */
export declare type Quota = Message<"routeiq.v1.admin.Quota"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: routeiq.v1.admin.Tier tier = 2;
   */
  tier: Tier;

  /**
   * @generated from field: int64 events_per_month = 3;
   */
  eventsPerMonth: bigint;

  /**
   * @generated from field: int64 frontier_calls_per_month = 4;
   */
  frontierCallsPerMonth: bigint;

  /**
   * @generated from field: int64 retention_days = 5;
   */
  retentionDays: bigint;
};

/**
 * Describes the message routeiq.v1.admin.Quota.
 * Use `create(QuotaSchema)` to create a new message.
 */
export declare const QuotaSchema: GenMessage<Quota>;

/**
 * @generated from message routeiq.v1.admin.GetUsageRequest
 */
export declare type GetUsageRequest = Message<"routeiq.v1.admin.GetUsageRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: google.protobuf.Timestamp period_start = 2;
   */
  periodStart?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp period_end = 3;
   */
  periodEnd?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.admin.GetUsageRequest.
 * Use `create(GetUsageRequestSchema)` to create a new message.
 */
export declare const GetUsageRequestSchema: GenMessage<GetUsageRequest>;

/**
 * @generated from message routeiq.v1.admin.GetQuotaRequest
 */
export declare type GetQuotaRequest = Message<"routeiq.v1.admin.GetQuotaRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;
};

/**
 * Describes the message routeiq.v1.admin.GetQuotaRequest.
 * Use `create(GetQuotaRequestSchema)` to create a new message.
 */
export declare const GetQuotaRequestSchema: GenMessage<GetQuotaRequest>;

/**
 * @generated from service routeiq.v1.admin.BillingService
 */
export declare const BillingService: GenService<{
  /**
   * @generated from rpc routeiq.v1.admin.BillingService.GetUsage
   */
  getUsage: {
    methodKind: "unary";
    input: typeof GetUsageRequestSchema;
    output: typeof UsageSummarySchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.BillingService.GetQuota
   */
  getQuota: {
    methodKind: "unary";
    input: typeof GetQuotaRequestSchema;
    output: typeof QuotaSchema;
  },
}>;

