// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/billing.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetQuotaRequest, GetUsageRequest, Quota, UsageSummary } from "./billing_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.BillingService
 */
export declare const BillingService: {
  readonly typeName: "routeiq.v1.admin.BillingService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.admin.BillingService.GetUsage
     */
    readonly getUsage: {
      readonly name: "GetUsage",
      readonly I: typeof GetUsageRequest,
      readonly O: typeof UsageSummary,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.BillingService.GetQuota
     */
    readonly getQuota: {
      readonly name: "GetQuota",
      readonly I: typeof GetQuotaRequest,
      readonly O: typeof Quota,
      readonly kind: MethodKind.Unary,
    },
  }
};

