// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/identity.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ApiKey, AssignRoleRequest, CreateApiKeyRequest, GetUserRequest, InviteUserRequest, ListApiKeysRequest, ListApiKeysResponse, RevokeApiKeyRequest, RoleAssignment, User } from "./identity_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.IdentityService
 */
export const IdentityService = {
  typeName: "routeiq.v1.admin.IdentityService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.InviteUser
     */
    inviteUser: {
      name: "InviteUser",
      I: InviteUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.AssignRole
     */
    assignRole: {
      name: "AssignRole",
      I: AssignRoleRequest,
      O: RoleAssignment,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.CreateApiKey
     */
    createApiKey: {
      name: "CreateApiKey",
      I: CreateApiKeyRequest,
      O: ApiKey,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.RevokeApiKey
     */
    revokeApiKey: {
      name: "RevokeApiKey",
      I: RevokeApiKeyRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.ListApiKeys
     */
    listApiKeys: {
      name: "ListApiKeys",
      I: ListApiKeysRequest,
      O: ListApiKeysResponse,
      kind: MethodKind.Unary,
    },
  }
};

