// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/identity.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ApiKey, AssignRoleRequest, CreateApiKeyRequest, GetUserRequest, InviteUserRequest, ListApiKeysRequest, ListApiKeysResponse, RevokeApiKeyRequest, RoleAssignment, User } from "./identity_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.IdentityService
 */
export declare const IdentityService: {
  readonly typeName: "routeiq.v1.admin.IdentityService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.InviteUser
     */
    readonly inviteUser: {
      readonly name: "InviteUser",
      readonly I: typeof InviteUserRequest,
      readonly O: typeof User,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.GetUser
     */
    readonly getUser: {
      readonly name: "GetUser",
      readonly I: typeof GetUserRequest,
      readonly O: typeof User,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.AssignRole
     */
    readonly assignRole: {
      readonly name: "AssignRole",
      readonly I: typeof AssignRoleRequest,
      readonly O: typeof RoleAssignment,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.CreateApiKey
     */
    readonly createApiKey: {
      readonly name: "CreateApiKey",
      readonly I: typeof CreateApiKeyRequest,
      readonly O: typeof ApiKey,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.RevokeApiKey
     */
    readonly revokeApiKey: {
      readonly name: "RevokeApiKey",
      readonly I: typeof RevokeApiKeyRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.IdentityService.ListApiKeys
     */
    readonly listApiKeys: {
      readonly name: "ListApiKeys",
      readonly I: typeof ListApiKeysRequest,
      readonly O: typeof ListApiKeysResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

