// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/identity.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/admin/identity.proto.
 */
export declare const file_routeiq_v1_admin_identity: GenFile;

/**
 * @generated from message routeiq.v1.admin.User
 */
export declare type User = Message<"routeiq.v1.admin.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: routeiq.v1.admin.AuthProvider auth_provider = 4;
   */
  authProvider: AuthProvider;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.admin.User.
 * Use `create(UserSchema)` to create a new message.
 */
export declare const UserSchema: GenMessage<User>;

/**
 * @generated from message routeiq.v1.admin.RoleAssignment
 */
export declare type RoleAssignment = Message<"routeiq.v1.admin.RoleAssignment"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: routeiq.v1.admin.Role role = 3;
   */
  role: Role;
};

/**
 * Describes the message routeiq.v1.admin.RoleAssignment.
 * Use `create(RoleAssignmentSchema)` to create a new message.
 */
export declare const RoleAssignmentSchema: GenMessage<RoleAssignment>;

/**
 * @generated from message routeiq.v1.admin.ApiKey
 */
export declare type ApiKey = Message<"routeiq.v1.admin.ApiKey"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 3;
   */
  workspaceId: string;

  /**
   * @generated from field: string prefix = 4;
   */
  prefix: string;

  /**
   * @generated from field: routeiq.v1.admin.ApiKeyScope scope = 5;
   */
  scope: ApiKeyScope;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 7;
   */
  expiresAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.admin.ApiKey.
 * Use `create(ApiKeySchema)` to create a new message.
 */
export declare const ApiKeySchema: GenMessage<ApiKey>;

/**
 * @generated from message routeiq.v1.admin.InviteUserRequest
 */
export declare type InviteUserRequest = Message<"routeiq.v1.admin.InviteUserRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: routeiq.v1.admin.Role role = 3;
   */
  role: Role;
};

/**
 * Describes the message routeiq.v1.admin.InviteUserRequest.
 * Use `create(InviteUserRequestSchema)` to create a new message.
 */
export declare const InviteUserRequestSchema: GenMessage<InviteUserRequest>;

/**
 * @generated from message routeiq.v1.admin.GetUserRequest
 */
export declare type GetUserRequest = Message<"routeiq.v1.admin.GetUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message routeiq.v1.admin.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export declare const GetUserRequestSchema: GenMessage<GetUserRequest>;

/**
 * @generated from message routeiq.v1.admin.AssignRoleRequest
 */
export declare type AssignRoleRequest = Message<"routeiq.v1.admin.AssignRoleRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: routeiq.v1.admin.Role role = 3;
   */
  role: Role;
};

/**
 * Describes the message routeiq.v1.admin.AssignRoleRequest.
 * Use `create(AssignRoleRequestSchema)` to create a new message.
 */
export declare const AssignRoleRequestSchema: GenMessage<AssignRoleRequest>;

/**
 * @generated from message routeiq.v1.admin.CreateApiKeyRequest
 */
export declare type CreateApiKeyRequest = Message<"routeiq.v1.admin.CreateApiKeyRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: routeiq.v1.admin.ApiKeyScope scope = 3;
   */
  scope: ApiKeyScope;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.admin.CreateApiKeyRequest.
 * Use `create(CreateApiKeyRequestSchema)` to create a new message.
 */
export declare const CreateApiKeyRequestSchema: GenMessage<CreateApiKeyRequest>;

/**
 * @generated from message routeiq.v1.admin.RevokeApiKeyRequest
 */
export declare type RevokeApiKeyRequest = Message<"routeiq.v1.admin.RevokeApiKeyRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message routeiq.v1.admin.RevokeApiKeyRequest.
 * Use `create(RevokeApiKeyRequestSchema)` to create a new message.
 */
export declare const RevokeApiKeyRequestSchema: GenMessage<RevokeApiKeyRequest>;

/**
 * @generated from message routeiq.v1.admin.ListApiKeysRequest
 */
export declare type ListApiKeysRequest = Message<"routeiq.v1.admin.ListApiKeysRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;
};

/**
 * Describes the message routeiq.v1.admin.ListApiKeysRequest.
 * Use `create(ListApiKeysRequestSchema)` to create a new message.
 */
export declare const ListApiKeysRequestSchema: GenMessage<ListApiKeysRequest>;

/**
 * @generated from message routeiq.v1.admin.ListApiKeysResponse
 */
export declare type ListApiKeysResponse = Message<"routeiq.v1.admin.ListApiKeysResponse"> & {
  /**
   * @generated from field: repeated routeiq.v1.admin.ApiKey api_keys = 1;
   */
  apiKeys: ApiKey[];
};

/**
 * Describes the message routeiq.v1.admin.ListApiKeysResponse.
 * Use `create(ListApiKeysResponseSchema)` to create a new message.
 */
export declare const ListApiKeysResponseSchema: GenMessage<ListApiKeysResponse>;

/**
 * @generated from enum routeiq.v1.admin.Role
 */
export enum Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  ROLE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: VIEWER = 1;
   */
  VIEWER = 1,

  /**
   * @generated from enum value: ANALYST = 2;
   */
  ANALYST = 2,

  /**
   * @generated from enum value: ADMIN = 3;
   */
  ADMIN = 3,

  /**
   * @generated from enum value: OWNER = 4;
   */
  OWNER = 4,
}

/**
 * Describes the enum routeiq.v1.admin.Role.
 */
export declare const RoleSchema: GenEnum<Role>;

/**
 * @generated from enum routeiq.v1.admin.AuthProvider
 */
export enum AuthProvider {
  /**
   * @generated from enum value: AUTH_PROVIDER_UNSPECIFIED = 0;
   */
  AUTH_PROVIDER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: GOOGLE = 1;
   */
  GOOGLE = 1,

  /**
   * @generated from enum value: GITHUB = 2;
   */
  GITHUB = 2,

  /**
   * @generated from enum value: SAML = 3;
   */
  SAML = 3,
}

/**
 * Describes the enum routeiq.v1.admin.AuthProvider.
 */
export declare const AuthProviderSchema: GenEnum<AuthProvider>;

/**
 * @generated from enum routeiq.v1.admin.ApiKeyScope
 */
export enum ApiKeyScope {
  /**
   * @generated from enum value: API_KEY_SCOPE_UNSPECIFIED = 0;
   */
  API_KEY_SCOPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: INGEST_ONLY = 1;
   */
  INGEST_ONLY = 1,

  /**
   * @generated from enum value: INGEST_AND_CONTROL = 2;
   */
  INGEST_AND_CONTROL = 2,

  /**
   * @generated from enum value: ADMIN_SCOPE = 3;
   */
  ADMIN_SCOPE = 3,
}

/**
 * Describes the enum routeiq.v1.admin.ApiKeyScope.
 */
export declare const ApiKeyScopeSchema: GenEnum<ApiKeyScope>;

/**
 * @generated from service routeiq.v1.admin.IdentityService
 */
export declare const IdentityService: GenService<{
  /**
   * @generated from rpc routeiq.v1.admin.IdentityService.InviteUser
   */
  inviteUser: {
    methodKind: "unary";
    input: typeof InviteUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.IdentityService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.IdentityService.AssignRole
   */
  assignRole: {
    methodKind: "unary";
    input: typeof AssignRoleRequestSchema;
    output: typeof RoleAssignmentSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.IdentityService.CreateApiKey
   */
  createApiKey: {
    methodKind: "unary";
    input: typeof CreateApiKeyRequestSchema;
    output: typeof ApiKeySchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.IdentityService.RevokeApiKey
   */
  revokeApiKey: {
    methodKind: "unary";
    input: typeof RevokeApiKeyRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.IdentityService.ListApiKeys
   */
  listApiKeys: {
    methodKind: "unary";
    input: typeof ListApiKeysRequestSchema;
    output: typeof ListApiKeysResponseSchema;
  },
}>;

