// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/organization.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateOrganizationRequest, CreateWorkspaceRequest, DeleteOrganizationRequest, GetOrganizationRequest, ListOrganizationsRequest, ListOrganizationsResponse, ListWorkspacesRequest, ListWorkspacesResponse, Organization, UpdateOrganizationRequest, UpdateWorkspaceRequest, Workspace } from "./organization_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.OrganizationService
 */
export const OrganizationService = {
  typeName: "routeiq.v1.admin.OrganizationService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.CreateOrganization
     */
    createOrganization: {
      name: "CreateOrganization",
      I: CreateOrganizationRequest,
      O: Organization,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.GetOrganization
     */
    getOrganization: {
      name: "GetOrganization",
      I: GetOrganizationRequest,
      O: Organization,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.ListOrganizations
     */
    listOrganizations: {
      name: "ListOrganizations",
      I: ListOrganizationsRequest,
      O: ListOrganizationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.UpdateOrganization
     */
    updateOrganization: {
      name: "UpdateOrganization",
      I: UpdateOrganizationRequest,
      O: Organization,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.DeleteOrganization
     */
    deleteOrganization: {
      name: "DeleteOrganization",
      I: DeleteOrganizationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.CreateWorkspace
     */
    createWorkspace: {
      name: "CreateWorkspace",
      I: CreateWorkspaceRequest,
      O: Workspace,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.ListWorkspaces
     */
    listWorkspaces: {
      name: "ListWorkspaces",
      I: ListWorkspacesRequest,
      O: ListWorkspacesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.UpdateWorkspace
     */
    updateWorkspace: {
      name: "UpdateWorkspace",
      I: UpdateWorkspaceRequest,
      O: Workspace,
      kind: MethodKind.Unary,
    },
  }
};

