// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/organization.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/admin/organization.proto.
 */
export declare const file_routeiq_v1_admin_organization: GenFile;

/**
 * @generated from message routeiq.v1.admin.Organization
 */
export declare type Organization = Message<"routeiq.v1.admin.Organization"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: routeiq.v1.admin.Tier tier = 3;
   */
  tier: Tier;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: repeated routeiq.v1.admin.Workspace workspaces = 5;
   */
  workspaces: Workspace[];
};

/**
 * Describes the message routeiq.v1.admin.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export declare const OrganizationSchema: GenMessage<Organization>;

/**
 * @generated from message routeiq.v1.admin.Workspace
 */
export declare type Workspace = Message<"routeiq.v1.admin.Workspace"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string environment = 4;
   */
  environment: string;

  /**
   * @generated from field: routeiq.v1.admin.Region region = 5;
   */
  region: Region;

  /**
   * @generated from field: routeiq.v1.admin.RetentionConfig retention = 6;
   */
  retention?: RetentionConfig | undefined;
};

/**
 * Describes the message routeiq.v1.admin.Workspace.
 * Use `create(WorkspaceSchema)` to create a new message.
 */
export declare const WorkspaceSchema: GenMessage<Workspace>;

/**
 * @generated from message routeiq.v1.admin.RetentionConfig
 */
export declare type RetentionConfig = Message<"routeiq.v1.admin.RetentionConfig"> & {
  /**
   * @generated from field: int32 hot_days = 1;
   */
  hotDays: number;

  /**
   * @generated from field: int32 warm_days = 2;
   */
  warmDays: number;

  /**
   * @generated from field: int32 cold_days = 3;
   */
  coldDays: number;
};

/**
 * Describes the message routeiq.v1.admin.RetentionConfig.
 * Use `create(RetentionConfigSchema)` to create a new message.
 */
export declare const RetentionConfigSchema: GenMessage<RetentionConfig>;

/**
 * @generated from message routeiq.v1.admin.CreateOrganizationRequest
 */
export declare type CreateOrganizationRequest = Message<"routeiq.v1.admin.CreateOrganizationRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: routeiq.v1.admin.Tier tier = 2;
   */
  tier: Tier;
};

/**
 * Describes the message routeiq.v1.admin.CreateOrganizationRequest.
 * Use `create(CreateOrganizationRequestSchema)` to create a new message.
 */
export declare const CreateOrganizationRequestSchema: GenMessage<CreateOrganizationRequest>;

/**
 * @generated from message routeiq.v1.admin.GetOrganizationRequest
 */
export declare type GetOrganizationRequest = Message<"routeiq.v1.admin.GetOrganizationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message routeiq.v1.admin.GetOrganizationRequest.
 * Use `create(GetOrganizationRequestSchema)` to create a new message.
 */
export declare const GetOrganizationRequestSchema: GenMessage<GetOrganizationRequest>;

/**
 * @generated from message routeiq.v1.admin.ListOrganizationsRequest
 */
export declare type ListOrganizationsRequest = Message<"routeiq.v1.admin.ListOrganizationsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message routeiq.v1.admin.ListOrganizationsRequest.
 * Use `create(ListOrganizationsRequestSchema)` to create a new message.
 */
export declare const ListOrganizationsRequestSchema: GenMessage<ListOrganizationsRequest>;

/**
 * @generated from message routeiq.v1.admin.ListOrganizationsResponse
 */
export declare type ListOrganizationsResponse = Message<"routeiq.v1.admin.ListOrganizationsResponse"> & {
  /**
   * @generated from field: repeated routeiq.v1.admin.Organization organizations = 1;
   */
  organizations: Organization[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message routeiq.v1.admin.ListOrganizationsResponse.
 * Use `create(ListOrganizationsResponseSchema)` to create a new message.
 */
export declare const ListOrganizationsResponseSchema: GenMessage<ListOrganizationsResponse>;

/**
 * @generated from message routeiq.v1.admin.UpdateOrganizationRequest
 */
export declare type UpdateOrganizationRequest = Message<"routeiq.v1.admin.UpdateOrganizationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: routeiq.v1.admin.Tier tier = 3;
   */
  tier: Tier;
};

/**
 * Describes the message routeiq.v1.admin.UpdateOrganizationRequest.
 * Use `create(UpdateOrganizationRequestSchema)` to create a new message.
 */
export declare const UpdateOrganizationRequestSchema: GenMessage<UpdateOrganizationRequest>;

/**
 * @generated from message routeiq.v1.admin.DeleteOrganizationRequest
 */
export declare type DeleteOrganizationRequest = Message<"routeiq.v1.admin.DeleteOrganizationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message routeiq.v1.admin.DeleteOrganizationRequest.
 * Use `create(DeleteOrganizationRequestSchema)` to create a new message.
 */
export declare const DeleteOrganizationRequestSchema: GenMessage<DeleteOrganizationRequest>;

/**
 * @generated from message routeiq.v1.admin.CreateWorkspaceRequest
 */
export declare type CreateWorkspaceRequest = Message<"routeiq.v1.admin.CreateWorkspaceRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string environment = 3;
   */
  environment: string;

  /**
   * @generated from field: routeiq.v1.admin.Region region = 4;
   */
  region: Region;
};

/**
 * Describes the message routeiq.v1.admin.CreateWorkspaceRequest.
 * Use `create(CreateWorkspaceRequestSchema)` to create a new message.
 */
export declare const CreateWorkspaceRequestSchema: GenMessage<CreateWorkspaceRequest>;

/**
 * @generated from message routeiq.v1.admin.ListWorkspacesRequest
 */
export declare type ListWorkspacesRequest = Message<"routeiq.v1.admin.ListWorkspacesRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;
};

/**
 * Describes the message routeiq.v1.admin.ListWorkspacesRequest.
 * Use `create(ListWorkspacesRequestSchema)` to create a new message.
 */
export declare const ListWorkspacesRequestSchema: GenMessage<ListWorkspacesRequest>;

/**
 * @generated from message routeiq.v1.admin.ListWorkspacesResponse
 */
export declare type ListWorkspacesResponse = Message<"routeiq.v1.admin.ListWorkspacesResponse"> & {
  /**
   * @generated from field: repeated routeiq.v1.admin.Workspace workspaces = 1;
   */
  workspaces: Workspace[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message routeiq.v1.admin.ListWorkspacesResponse.
 * Use `create(ListWorkspacesResponseSchema)` to create a new message.
 */
export declare const ListWorkspacesResponseSchema: GenMessage<ListWorkspacesResponse>;

/**
 * @generated from message routeiq.v1.admin.UpdateWorkspaceRequest
 */
export declare type UpdateWorkspaceRequest = Message<"routeiq.v1.admin.UpdateWorkspaceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: routeiq.v1.admin.RetentionConfig retention = 3;
   */
  retention?: RetentionConfig | undefined;
};

/**
 * Describes the message routeiq.v1.admin.UpdateWorkspaceRequest.
 * Use `create(UpdateWorkspaceRequestSchema)` to create a new message.
 */
export declare const UpdateWorkspaceRequestSchema: GenMessage<UpdateWorkspaceRequest>;

/**
 * @generated from enum routeiq.v1.admin.Tier
 */
export enum Tier {
  /**
   * @generated from enum value: TIER_UNSPECIFIED = 0;
   */
  TIER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: FREE = 1;
   */
  FREE = 1,

  /**
   * @generated from enum value: GROWTH = 2;
   */
  GROWTH = 2,

  /**
   * @generated from enum value: PRO = 3;
   */
  PRO = 3,

  /**
   * @generated from enum value: ENTERPRISE = 4;
   */
  ENTERPRISE = 4,
}

/**
 * Describes the enum routeiq.v1.admin.Tier.
 */
export declare const TierSchema: GenEnum<Tier>;

/**
 * @generated from enum routeiq.v1.admin.Region
 */
export enum Region {
  /**
   * @generated from enum value: REGION_UNSPECIFIED = 0;
   */
  REGION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: US_EAST_1 = 1;
   */
  US_EAST_1 = 1,

  /**
   * @generated from enum value: US_WEST_2 = 2;
   */
  US_WEST_2 = 2,

  /**
   * @generated from enum value: EU_WEST_1 = 3;
   */
  EU_WEST_1 = 3,

  /**
   * @generated from enum value: AP_SOUTHEAST_1 = 4;
   */
  AP_SOUTHEAST_1 = 4,
}

/**
 * Describes the enum routeiq.v1.admin.Region.
 */
export declare const RegionSchema: GenEnum<Region>;

/**
 * @generated from service routeiq.v1.admin.OrganizationService
 */
export declare const OrganizationService: GenService<{
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.CreateOrganization
   */
  createOrganization: {
    methodKind: "unary";
    input: typeof CreateOrganizationRequestSchema;
    output: typeof OrganizationSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.GetOrganization
   */
  getOrganization: {
    methodKind: "unary";
    input: typeof GetOrganizationRequestSchema;
    output: typeof OrganizationSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.ListOrganizations
   */
  listOrganizations: {
    methodKind: "unary";
    input: typeof ListOrganizationsRequestSchema;
    output: typeof ListOrganizationsResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.UpdateOrganization
   */
  updateOrganization: {
    methodKind: "unary";
    input: typeof UpdateOrganizationRequestSchema;
    output: typeof OrganizationSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.DeleteOrganization
   */
  deleteOrganization: {
    methodKind: "unary";
    input: typeof DeleteOrganizationRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.CreateWorkspace
   */
  createWorkspace: {
    methodKind: "unary";
    input: typeof CreateWorkspaceRequestSchema;
    output: typeof WorkspaceSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.ListWorkspaces
   */
  listWorkspaces: {
    methodKind: "unary";
    input: typeof ListWorkspacesRequestSchema;
    output: typeof ListWorkspacesResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.OrganizationService.UpdateWorkspace
   */
  updateWorkspace: {
    methodKind: "unary";
    input: typeof UpdateWorkspaceRequestSchema;
    output: typeof WorkspaceSchema;
  },
}>;

