// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/organization.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateOrganizationRequest, CreateWorkspaceRequest, DeleteOrganizationRequest, GetOrganizationRequest, ListOrganizationsRequest, ListOrganizationsResponse, ListWorkspacesRequest, ListWorkspacesResponse, Organization, UpdateOrganizationRequest, UpdateWorkspaceRequest, Workspace } from "./organization_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.OrganizationService
 */
export declare const OrganizationService: {
  readonly typeName: "routeiq.v1.admin.OrganizationService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.CreateOrganization
     */
    readonly createOrganization: {
      readonly name: "CreateOrganization",
      readonly I: typeof CreateOrganizationRequest,
      readonly O: typeof Organization,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.GetOrganization
     */
    readonly getOrganization: {
      readonly name: "GetOrganization",
      readonly I: typeof GetOrganizationRequest,
      readonly O: typeof Organization,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.ListOrganizations
     */
    readonly listOrganizations: {
      readonly name: "ListOrganizations",
      readonly I: typeof ListOrganizationsRequest,
      readonly O: typeof ListOrganizationsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.UpdateOrganization
     */
    readonly updateOrganization: {
      readonly name: "UpdateOrganization",
      readonly I: typeof UpdateOrganizationRequest,
      readonly O: typeof Organization,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.DeleteOrganization
     */
    readonly deleteOrganization: {
      readonly name: "DeleteOrganization",
      readonly I: typeof DeleteOrganizationRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.CreateWorkspace
     */
    readonly createWorkspace: {
      readonly name: "CreateWorkspace",
      readonly I: typeof CreateWorkspaceRequest,
      readonly O: typeof Workspace,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.ListWorkspaces
     */
    readonly listWorkspaces: {
      readonly name: "ListWorkspaces",
      readonly I: typeof ListWorkspacesRequest,
      readonly O: typeof ListWorkspacesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.OrganizationService.UpdateWorkspace
     */
    readonly updateWorkspace: {
      readonly name: "UpdateWorkspace",
      readonly I: typeof UpdateWorkspaceRequest,
      readonly O: typeof Workspace,
      readonly kind: MethodKind.Unary,
    },
  }
};

