// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/policy.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/admin/policy.proto.
 */
export declare const file_routeiq_v1_admin_policy: GenFile;

/**
 * @generated from message routeiq.v1.admin.PolicyBundle
 */
export declare type PolicyBundle = Message<"routeiq.v1.admin.PolicyBundle"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 3;
   */
  workspaceId: string;

  /**
   * @generated from field: string version = 4;
   */
  version: string;

  /**
   * @generated from field: bytes content = 5;
   */
  content: Uint8Array;

  /**
   * @generated from field: bool active = 6;
   */
  active: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.admin.PolicyBundle.
 * Use `create(PolicyBundleSchema)` to create a new message.
 */
export declare const PolicyBundleSchema: GenMessage<PolicyBundle>;

/**
 * @generated from message routeiq.v1.admin.CreatePolicyBundleRequest
 */
export declare type CreatePolicyBundleRequest = Message<"routeiq.v1.admin.CreatePolicyBundleRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: bytes content = 3;
   */
  content: Uint8Array;
};

/**
 * Describes the message routeiq.v1.admin.CreatePolicyBundleRequest.
 * Use `create(CreatePolicyBundleRequestSchema)` to create a new message.
 */
export declare const CreatePolicyBundleRequestSchema: GenMessage<CreatePolicyBundleRequest>;

/**
 * @generated from message routeiq.v1.admin.GetPolicyBundleRequest
 */
export declare type GetPolicyBundleRequest = Message<"routeiq.v1.admin.GetPolicyBundleRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message routeiq.v1.admin.GetPolicyBundleRequest.
 * Use `create(GetPolicyBundleRequestSchema)` to create a new message.
 */
export declare const GetPolicyBundleRequestSchema: GenMessage<GetPolicyBundleRequest>;

/**
 * @generated from message routeiq.v1.admin.ListPolicyBundlesRequest
 */
export declare type ListPolicyBundlesRequest = Message<"routeiq.v1.admin.ListPolicyBundlesRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: bool active_only = 2;
   */
  activeOnly: boolean;
};

/**
 * Describes the message routeiq.v1.admin.ListPolicyBundlesRequest.
 * Use `create(ListPolicyBundlesRequestSchema)` to create a new message.
 */
export declare const ListPolicyBundlesRequestSchema: GenMessage<ListPolicyBundlesRequest>;

/**
 * @generated from message routeiq.v1.admin.ListPolicyBundlesResponse
 */
export declare type ListPolicyBundlesResponse = Message<"routeiq.v1.admin.ListPolicyBundlesResponse"> & {
  /**
   * @generated from field: repeated routeiq.v1.admin.PolicyBundle bundles = 1;
   */
  bundles: PolicyBundle[];
};

/**
 * Describes the message routeiq.v1.admin.ListPolicyBundlesResponse.
 * Use `create(ListPolicyBundlesResponseSchema)` to create a new message.
 */
export declare const ListPolicyBundlesResponseSchema: GenMessage<ListPolicyBundlesResponse>;

/**
 * @generated from message routeiq.v1.admin.ActivatePolicyBundleRequest
 */
export declare type ActivatePolicyBundleRequest = Message<"routeiq.v1.admin.ActivatePolicyBundleRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message routeiq.v1.admin.ActivatePolicyBundleRequest.
 * Use `create(ActivatePolicyBundleRequestSchema)` to create a new message.
 */
export declare const ActivatePolicyBundleRequestSchema: GenMessage<ActivatePolicyBundleRequest>;

/**
 * @generated from message routeiq.v1.admin.DeletePolicyBundleRequest
 */
export declare type DeletePolicyBundleRequest = Message<"routeiq.v1.admin.DeletePolicyBundleRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message routeiq.v1.admin.DeletePolicyBundleRequest.
 * Use `create(DeletePolicyBundleRequestSchema)` to create a new message.
 */
export declare const DeletePolicyBundleRequestSchema: GenMessage<DeletePolicyBundleRequest>;

/**
 * @generated from service routeiq.v1.admin.PolicyService
 */
export declare const PolicyService: GenService<{
  /**
   * @generated from rpc routeiq.v1.admin.PolicyService.CreatePolicyBundle
   */
  createPolicyBundle: {
    methodKind: "unary";
    input: typeof CreatePolicyBundleRequestSchema;
    output: typeof PolicyBundleSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.PolicyService.GetPolicyBundle
   */
  getPolicyBundle: {
    methodKind: "unary";
    input: typeof GetPolicyBundleRequestSchema;
    output: typeof PolicyBundleSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.PolicyService.ListPolicyBundles
   */
  listPolicyBundles: {
    methodKind: "unary";
    input: typeof ListPolicyBundlesRequestSchema;
    output: typeof ListPolicyBundlesResponseSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.PolicyService.ActivatePolicyBundle
   */
  activatePolicyBundle: {
    methodKind: "unary";
    input: typeof ActivatePolicyBundleRequestSchema;
    output: typeof PolicyBundleSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.PolicyService.DeletePolicyBundle
   */
  deletePolicyBundle: {
    methodKind: "unary";
    input: typeof DeletePolicyBundleRequestSchema;
    output: typeof EmptySchema;
  },
}>;

