// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/policy.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivatePolicyBundleRequest, CreatePolicyBundleRequest, DeletePolicyBundleRequest, GetPolicyBundleRequest, ListPolicyBundlesRequest, ListPolicyBundlesResponse, PolicyBundle } from "./policy_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.PolicyService
 */
export declare const PolicyService: {
  readonly typeName: "routeiq.v1.admin.PolicyService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.CreatePolicyBundle
     */
    readonly createPolicyBundle: {
      readonly name: "CreatePolicyBundle",
      readonly I: typeof CreatePolicyBundleRequest,
      readonly O: typeof PolicyBundle,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.GetPolicyBundle
     */
    readonly getPolicyBundle: {
      readonly name: "GetPolicyBundle",
      readonly I: typeof GetPolicyBundleRequest,
      readonly O: typeof PolicyBundle,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.ListPolicyBundles
     */
    readonly listPolicyBundles: {
      readonly name: "ListPolicyBundles",
      readonly I: typeof ListPolicyBundlesRequest,
      readonly O: typeof ListPolicyBundlesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.ActivatePolicyBundle
     */
    readonly activatePolicyBundle: {
      readonly name: "ActivatePolicyBundle",
      readonly I: typeof ActivatePolicyBundleRequest,
      readonly O: typeof PolicyBundle,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.DeletePolicyBundle
     */
    readonly deletePolicyBundle: {
      readonly name: "DeletePolicyBundle",
      readonly I: typeof DeletePolicyBundleRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

