// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/policy.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/admin/policy.proto.
 */
export const file_routeiq_v1_admin_policy = /*@__PURE__*/
  fileDesc("Ch1yb3V0ZWlxL3YxL2FkbWluL3BvbGljeS5wcm90bxIQcm91dGVpcS52MS5hZG1pbiKrAQoMUG9saWN5QnVuZGxlEgoKAmlkGAEgASgJEhcKD29yZ2FuaXphdGlvbl9pZBgCIAEoCRIUCgx3b3Jrc3BhY2VfaWQYAyABKAkSDwoHdmVyc2lvbhgEIAEoCRIPCgdjb250ZW50GAUgASgMEg4KBmFjdGl2ZRgGIAEoCBIuCgpjcmVhdGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJbChlDcmVhdGVQb2xpY3lCdW5kbGVSZXF1ZXN0EhcKD29yZ2FuaXphdGlvbl9pZBgBIAEoCRIUCgx3b3Jrc3BhY2VfaWQYAiABKAkSDwoHY29udGVudBgDIAEoDCIkChZHZXRQb2xpY3lCdW5kbGVSZXF1ZXN0EgoKAmlkGAEgASgJIkUKGExpc3RQb2xpY3lCdW5kbGVzUmVxdWVzdBIUCgx3b3Jrc3BhY2VfaWQYASABKAkSEwoLYWN0aXZlX29ubHkYAiABKAgiTAoZTGlzdFBvbGljeUJ1bmRsZXNSZXNwb25zZRIvCgdidW5kbGVzGAEgAygLMh4ucm91dGVpcS52MS5hZG1pbi5Qb2xpY3lCdW5kbGUiKQobQWN0aXZhdGVQb2xpY3lCdW5kbGVSZXF1ZXN0EgoKAmlkGAEgASgJIicKGURlbGV0ZVBvbGljeUJ1bmRsZVJlcXVlc3QSCgoCaWQYASABKAky/wMKDVBvbGljeVNlcnZpY2USYQoSQ3JlYXRlUG9saWN5QnVuZGxlEisucm91dGVpcS52MS5hZG1pbi5DcmVhdGVQb2xpY3lCdW5kbGVSZXF1ZXN0Gh4ucm91dGVpcS52MS5hZG1pbi5Qb2xpY3lCdW5kbGUSWwoPR2V0UG9saWN5QnVuZGxlEigucm91dGVpcS52MS5hZG1pbi5HZXRQb2xpY3lCdW5kbGVSZXF1ZXN0Gh4ucm91dGVpcS52MS5hZG1pbi5Qb2xpY3lCdW5kbGUSbAoRTGlzdFBvbGljeUJ1bmRsZXMSKi5yb3V0ZWlxLnYxLmFkbWluLkxpc3RQb2xpY3lCdW5kbGVzUmVxdWVzdBorLnJvdXRlaXEudjEuYWRtaW4uTGlzdFBvbGljeUJ1bmRsZXNSZXNwb25zZRJlChRBY3RpdmF0ZVBvbGljeUJ1bmRsZRItLnJvdXRlaXEudjEuYWRtaW4uQWN0aXZhdGVQb2xpY3lCdW5kbGVSZXF1ZXN0Gh4ucm91dGVpcS52MS5hZG1pbi5Qb2xpY3lCdW5kbGUSWQoSRGVsZXRlUG9saWN5QnVuZGxlEisucm91dGVpcS52MS5hZG1pbi5EZWxldGVQb2xpY3lCdW5kbGVSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5QosBCi5idWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLmFkbWluQgtQb2xpY3lQcm90b1pMYnVmLmJ1aWxkL2dlbi9nby9zc2ZvcmdlL3JvdXRlaXEvcHJvdG9jb2xidWZmZXJzL2dvL3JvdXRlaXEvdjEvYWRtaW47YWRtaW52MWIGcHJvdG8z", [file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * Describes the message routeiq.v1.admin.PolicyBundle.
 * Use `create(PolicyBundleSchema)` to create a new message.
 */
export const PolicyBundleSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_policy, 0);

/**
 * Describes the message routeiq.v1.admin.CreatePolicyBundleRequest.
 * Use `create(CreatePolicyBundleRequestSchema)` to create a new message.
 */
export const CreatePolicyBundleRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_policy, 1);

/**
 * Describes the message routeiq.v1.admin.GetPolicyBundleRequest.
 * Use `create(GetPolicyBundleRequestSchema)` to create a new message.
 */
export const GetPolicyBundleRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_policy, 2);

/**
 * Describes the message routeiq.v1.admin.ListPolicyBundlesRequest.
 * Use `create(ListPolicyBundlesRequestSchema)` to create a new message.
 */
export const ListPolicyBundlesRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_policy, 3);

/**
 * Describes the message routeiq.v1.admin.ListPolicyBundlesResponse.
 * Use `create(ListPolicyBundlesResponseSchema)` to create a new message.
 */
export const ListPolicyBundlesResponseSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_policy, 4);

/**
 * Describes the message routeiq.v1.admin.ActivatePolicyBundleRequest.
 * Use `create(ActivatePolicyBundleRequestSchema)` to create a new message.
 */
export const ActivatePolicyBundleRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_policy, 5);

/**
 * Describes the message routeiq.v1.admin.DeletePolicyBundleRequest.
 * Use `create(DeletePolicyBundleRequestSchema)` to create a new message.
 */
export const DeletePolicyBundleRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_policy, 6);

/**
 * @generated from service routeiq.v1.admin.PolicyService
 */
export const PolicyService = /*@__PURE__*/
  serviceDesc(file_routeiq_v1_admin_policy, 0);

