// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/policy.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivatePolicyBundleRequest, CreatePolicyBundleRequest, DeletePolicyBundleRequest, GetPolicyBundleRequest, ListPolicyBundlesRequest, ListPolicyBundlesResponse, PolicyBundle } from "./policy_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.PolicyService
 */
export const PolicyService = {
  typeName: "routeiq.v1.admin.PolicyService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.CreatePolicyBundle
     */
    createPolicyBundle: {
      name: "CreatePolicyBundle",
      I: CreatePolicyBundleRequest,
      O: PolicyBundle,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.GetPolicyBundle
     */
    getPolicyBundle: {
      name: "GetPolicyBundle",
      I: GetPolicyBundleRequest,
      O: PolicyBundle,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.ListPolicyBundles
     */
    listPolicyBundles: {
      name: "ListPolicyBundles",
      I: ListPolicyBundlesRequest,
      O: ListPolicyBundlesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.ActivatePolicyBundle
     */
    activatePolicyBundle: {
      name: "ActivatePolicyBundle",
      I: ActivatePolicyBundleRequest,
      O: PolicyBundle,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.PolicyService.DeletePolicyBundle
     */
    deletePolicyBundle: {
      name: "DeletePolicyBundle",
      I: DeletePolicyBundleRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

