// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/slo_config.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file routeiq/v1/admin/slo_config.proto.
 */
export const file_routeiq_v1_admin_slo_config = /*@__PURE__*/
  fileDesc("CiFyb3V0ZWlxL3YxL2FkbWluL3Nsb19jb25maWcucHJvdG8SEHJvdXRlaXEudjEuYWRtaW4iXwoLU2xvT3ZlcnJpZGUSEQoJbWV0cmljX2lkGAEgASgJEhQKDHdvcmtzcGFjZV9pZBgCIAEoCRIMCgR0aWVyGAMgASgJEhkKEXRhcmdldF9leHByZXNzaW9uGAQgASgJIlYKDFNsb092ZXJyaWRlcxIUCgx3b3Jrc3BhY2VfaWQYASABKAkSMAoJb3ZlcnJpZGVzGAIgAygLMh0ucm91dGVpcS52MS5hZG1pbi5TbG9PdmVycmlkZSIuChZHZXRTbG9PdmVycmlkZXNSZXF1ZXN0EhQKDHdvcmtzcGFjZV9pZBgBIAEoCSJIChVTZXRTbG9PdmVycmlkZVJlcXVlc3QSLwoIb3ZlcnJpZGUYASABKAsyHS5yb3V0ZWlxLnYxLmFkbWluLlNsb092ZXJyaWRlIlEKGERlbGV0ZVNsb092ZXJyaWRlUmVxdWVzdBIRCgltZXRyaWNfaWQYASABKAkSFAoMd29ya3NwYWNlX2lkGAIgASgJEgwKBHRpZXIYAyABKAkyqgIKEFNsb0NvbmZpZ1NlcnZpY2USWwoPR2V0U2xvT3ZlcnJpZGVzEigucm91dGVpcS52MS5hZG1pbi5HZXRTbG9PdmVycmlkZXNSZXF1ZXN0Gh4ucm91dGVpcS52MS5hZG1pbi5TbG9PdmVycmlkZXMSWAoOU2V0U2xvT3ZlcnJpZGUSJy5yb3V0ZWlxLnYxLmFkbWluLlNldFNsb092ZXJyaWRlUmVxdWVzdBodLnJvdXRlaXEudjEuYWRtaW4uU2xvT3ZlcnJpZGUSXwoRRGVsZXRlU2xvT3ZlcnJpZGUSKi5yb3V0ZWlxLnYxLmFkbWluLkRlbGV0ZVNsb092ZXJyaWRlUmVxdWVzdBoeLnJvdXRlaXEudjEuYWRtaW4uU2xvT3ZlcnJpZGVzQo4BCi5idWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLmFkbWluQg5TbG9Db25maWdQcm90b1pMYnVmLmJ1aWxkL2dlbi9nby9zc2ZvcmdlL3JvdXRlaXEvcHJvdG9jb2xidWZmZXJzL2dvL3JvdXRlaXEvdjEvYWRtaW47YWRtaW52MWIGcHJvdG8z");

/**
 * Describes the message routeiq.v1.admin.SloOverride.
 * Use `create(SloOverrideSchema)` to create a new message.
 */
export const SloOverrideSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_slo_config, 0);

/**
 * Describes the message routeiq.v1.admin.SloOverrides.
 * Use `create(SloOverridesSchema)` to create a new message.
 */
export const SloOverridesSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_slo_config, 1);

/**
 * Describes the message routeiq.v1.admin.GetSloOverridesRequest.
 * Use `create(GetSloOverridesRequestSchema)` to create a new message.
 */
export const GetSloOverridesRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_slo_config, 2);

/**
 * Describes the message routeiq.v1.admin.SetSloOverrideRequest.
 * Use `create(SetSloOverrideRequestSchema)` to create a new message.
 */
export const SetSloOverrideRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_slo_config, 3);

/**
 * Describes the message routeiq.v1.admin.DeleteSloOverrideRequest.
 * Use `create(DeleteSloOverrideRequestSchema)` to create a new message.
 */
export const DeleteSloOverrideRequestSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_admin_slo_config, 4);

/**
 * @generated from service routeiq.v1.admin.SloConfigService
 */
export const SloConfigService = /*@__PURE__*/
  serviceDesc(file_routeiq_v1_admin_slo_config, 0);

