// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/slo_config.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteSloOverrideRequest, GetSloOverridesRequest, SetSloOverrideRequest, SloOverride, SloOverrides } from "./slo_config_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.SloConfigService
 */
export declare const SloConfigService: {
  readonly typeName: "routeiq.v1.admin.SloConfigService",
  readonly methods: {
    /**
     * @generated from rpc routeiq.v1.admin.SloConfigService.GetSloOverrides
     */
    readonly getSloOverrides: {
      readonly name: "GetSloOverrides",
      readonly I: typeof GetSloOverridesRequest,
      readonly O: typeof SloOverrides,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.SloConfigService.SetSloOverride
     */
    readonly setSloOverride: {
      readonly name: "SetSloOverride",
      readonly I: typeof SetSloOverrideRequest,
      readonly O: typeof SloOverride,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.SloConfigService.DeleteSloOverride
     */
    readonly deleteSloOverride: {
      readonly name: "DeleteSloOverride",
      readonly I: typeof DeleteSloOverrideRequest,
      readonly O: typeof SloOverrides,
      readonly kind: MethodKind.Unary,
    },
  }
};

