// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/admin/slo_config.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file routeiq/v1/admin/slo_config.proto.
 */
export declare const file_routeiq_v1_admin_slo_config: GenFile;

/**
 * @generated from message routeiq.v1.admin.SloOverride
 */
export declare type SloOverride = Message<"routeiq.v1.admin.SloOverride"> & {
  /**
   * @generated from field: string metric_id = 1;
   */
  metricId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string tier = 3;
   */
  tier: string;

  /**
   * @generated from field: string target_expression = 4;
   */
  targetExpression: string;
};

/**
 * Describes the message routeiq.v1.admin.SloOverride.
 * Use `create(SloOverrideSchema)` to create a new message.
 */
export declare const SloOverrideSchema: GenMessage<SloOverride>;

/**
 * @generated from message routeiq.v1.admin.SloOverrides
 */
export declare type SloOverrides = Message<"routeiq.v1.admin.SloOverrides"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: repeated routeiq.v1.admin.SloOverride overrides = 2;
   */
  overrides: SloOverride[];
};

/**
 * Describes the message routeiq.v1.admin.SloOverrides.
 * Use `create(SloOverridesSchema)` to create a new message.
 */
export declare const SloOverridesSchema: GenMessage<SloOverrides>;

/**
 * @generated from message routeiq.v1.admin.GetSloOverridesRequest
 */
export declare type GetSloOverridesRequest = Message<"routeiq.v1.admin.GetSloOverridesRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;
};

/**
 * Describes the message routeiq.v1.admin.GetSloOverridesRequest.
 * Use `create(GetSloOverridesRequestSchema)` to create a new message.
 */
export declare const GetSloOverridesRequestSchema: GenMessage<GetSloOverridesRequest>;

/**
 * @generated from message routeiq.v1.admin.SetSloOverrideRequest
 */
export declare type SetSloOverrideRequest = Message<"routeiq.v1.admin.SetSloOverrideRequest"> & {
  /**
   * @generated from field: routeiq.v1.admin.SloOverride override = 1;
   */
  override?: SloOverride | undefined;
};

/**
 * Describes the message routeiq.v1.admin.SetSloOverrideRequest.
 * Use `create(SetSloOverrideRequestSchema)` to create a new message.
 */
export declare const SetSloOverrideRequestSchema: GenMessage<SetSloOverrideRequest>;

/**
 * @generated from message routeiq.v1.admin.DeleteSloOverrideRequest
 */
export declare type DeleteSloOverrideRequest = Message<"routeiq.v1.admin.DeleteSloOverrideRequest"> & {
  /**
   * @generated from field: string metric_id = 1;
   */
  metricId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string tier = 3;
   */
  tier: string;
};

/**
 * Describes the message routeiq.v1.admin.DeleteSloOverrideRequest.
 * Use `create(DeleteSloOverrideRequestSchema)` to create a new message.
 */
export declare const DeleteSloOverrideRequestSchema: GenMessage<DeleteSloOverrideRequest>;

/**
 * @generated from service routeiq.v1.admin.SloConfigService
 */
export declare const SloConfigService: GenService<{
  /**
   * @generated from rpc routeiq.v1.admin.SloConfigService.GetSloOverrides
   */
  getSloOverrides: {
    methodKind: "unary";
    input: typeof GetSloOverridesRequestSchema;
    output: typeof SloOverridesSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.SloConfigService.SetSloOverride
   */
  setSloOverride: {
    methodKind: "unary";
    input: typeof SetSloOverrideRequestSchema;
    output: typeof SloOverrideSchema;
  },
  /**
   * @generated from rpc routeiq.v1.admin.SloConfigService.DeleteSloOverride
   */
  deleteSloOverride: {
    methodKind: "unary";
    input: typeof DeleteSloOverrideRequestSchema;
    output: typeof SloOverridesSchema;
  },
}>;

