// @generated by protoc-gen-connect-es v1.6.1
// @generated from file routeiq/v1/admin/slo_config.proto (package routeiq.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteSloOverrideRequest, GetSloOverridesRequest, SetSloOverrideRequest, SloOverride, SloOverrides } from "./slo_config_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service routeiq.v1.admin.SloConfigService
 */
export const SloConfigService = {
  typeName: "routeiq.v1.admin.SloConfigService",
  methods: {
    /**
     * @generated from rpc routeiq.v1.admin.SloConfigService.GetSloOverrides
     */
    getSloOverrides: {
      name: "GetSloOverrides",
      I: GetSloOverridesRequest,
      O: SloOverrides,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.SloConfigService.SetSloOverride
     */
    setSloOverride: {
      name: "SetSloOverride",
      I: SetSloOverrideRequest,
      O: SloOverride,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc routeiq.v1.admin.SloConfigService.DeleteSloOverride
     */
    deleteSloOverride: {
      name: "DeleteSloOverride",
      I: DeleteSloOverrideRequest,
      O: SloOverrides,
      kind: MethodKind.Unary,
    },
  }
};

