// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/alerts.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file routeiq/v1/insights/alerts.proto.
 */
export const file_routeiq_v1_insights_alerts = /*@__PURE__*/
  fileDesc("CiByb3V0ZWlxL3YxL2luc2lnaHRzL2FsZXJ0cy5wcm90bxITcm91dGVpcS52MS5pbnNpZ2h0cyLtAQoJQWxlcnRSdWxlEgoKAmlkGAEgASgJEhEKCW1ldHJpY19pZBgCIAEoCRIxCgljb25kaXRpb24YAyABKAsyHi5yb3V0ZWlxLnYxLmluc2lnaHRzLkNvbmRpdGlvbhIvCghzZXZlcml0eRgEIAEoDjIdLnJvdXRlaXEudjEuaW5zaWdodHMuU2V2ZXJpdHkSNwoHYWN0aW9ucxgFIAMoDjImLnJvdXRlaXEudjEuaW5zaWdodHMuUmVjb21tZW5kZWRBY3Rpb24SEwoLZGVzY3JpcHRpb24YBiABKAkSDwoHZW5hYmxlZBgHIAEoCCJuCglDb25kaXRpb24SKQoCb3AYASABKA4yHS5yb3V0ZWlxLnYxLmluc2lnaHRzLk9wZXJhdG9yEhEKCXRocmVzaG9sZBgCIAEoARIOCgZ3aW5kb3cYAyABKAkSEwoLbWluX3NhbXBsZXMYBCABKAUqbAoIT3BlcmF0b3ISGAoUT1BFUkFUT1JfVU5TUEVDSUZJRUQQABIGCgJHVBABEgYKAkxUEAISBwoDR1RFEAMSBwoDTFRFEAQSBgoCRVEQBRIMCghUUkVORF9VUBAGEg4KClRSRU5EX0RPV04QBypTCghTZXZlcml0eRIYChRTRVZFUklUWV9VTlNQRUNJRklFRBAAEggKBElORk8QARILCgdXQVJOSU5HEAISDAoIQ1JJVElDQUwQAxIICgRQQUdFEAQqpQEKEVJlY29tbWVuZGVkQWN0aW9uEhYKEkFDVElPTl9VTlNQRUNJRklFRBAAEhMKD1JFRFVDRV9BVVRPTk9NWRABEhEKDUNJUkNVSVRfQlJFQUsQAhISCg5FU0NBTEFURV9IVU1BThADEhQKEFJPTExCQUNLX1ZFUlNJT04QBBIQCgxTV0lUQ0hfTU9ERUwQBRIUChBSRVFVSVJFX0FQUFJPVkFMEAZClAEKMWJ1aWxkLmJ1Zi5nZW4uc3Nmb3JnZS5yb3V0ZWlxLnJvdXRlaXEudjEuaW5zaWdodHNCC0FsZXJ0c1Byb3RvWlJidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9pbnNpZ2h0cztpbnNpZ2h0c3YxYgZwcm90bzM");

/**
 * Describes the message routeiq.v1.insights.AlertRule.
 * Use `create(AlertRuleSchema)` to create a new message.
 */
export const AlertRuleSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_insights_alerts, 0);

/**
 * Describes the message routeiq.v1.insights.Condition.
 * Use `create(ConditionSchema)` to create a new message.
 */
export const ConditionSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_insights_alerts, 1);

/**
 * Describes the enum routeiq.v1.insights.Operator.
 */
export const OperatorSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_insights_alerts, 0);

/**
 * @generated from enum routeiq.v1.insights.Operator
 */
export const Operator = /*@__PURE__*/
  tsEnum(OperatorSchema);

/**
 * Describes the enum routeiq.v1.insights.Severity.
 */
export const SeveritySchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_insights_alerts, 1);

/**
 * @generated from enum routeiq.v1.insights.Severity
 */
export const Severity = /*@__PURE__*/
  tsEnum(SeveritySchema);

/**
 * Describes the enum routeiq.v1.insights.RecommendedAction.
 */
export const RecommendedActionSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_insights_alerts, 2);

/**
 * @generated from enum routeiq.v1.insights.RecommendedAction
 */
export const RecommendedAction = /*@__PURE__*/
  tsEnum(RecommendedActionSchema);

