// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/alerts.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file routeiq/v1/insights/alerts.proto.
 */
export declare const file_routeiq_v1_insights_alerts: GenFile;

/**
 * @generated from message routeiq.v1.insights.AlertRule
 */
export declare type AlertRule = Message<"routeiq.v1.insights.AlertRule"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string metric_id = 2;
   */
  metricId: string;

  /**
   * @generated from field: routeiq.v1.insights.Condition condition = 3;
   */
  condition?: Condition | undefined;

  /**
   * @generated from field: routeiq.v1.insights.Severity severity = 4;
   */
  severity: Severity;

  /**
   * @generated from field: repeated routeiq.v1.insights.RecommendedAction actions = 5;
   */
  actions: RecommendedAction[];

  /**
   * @generated from field: string description = 6;
   */
  description: string;

  /**
   * @generated from field: bool enabled = 7;
   */
  enabled: boolean;
};

/**
 * Describes the message routeiq.v1.insights.AlertRule.
 * Use `create(AlertRuleSchema)` to create a new message.
 */
export declare const AlertRuleSchema: GenMessage<AlertRule>;

/**
 * @generated from message routeiq.v1.insights.Condition
 */
export declare type Condition = Message<"routeiq.v1.insights.Condition"> & {
  /**
   * @generated from field: routeiq.v1.insights.Operator op = 1;
   */
  op: Operator;

  /**
   * @generated from field: double threshold = 2;
   */
  threshold: number;

  /**
   * @generated from field: string window = 3;
   */
  window: string;

  /**
   * @generated from field: int32 min_samples = 4;
   */
  minSamples: number;
};

/**
 * Describes the message routeiq.v1.insights.Condition.
 * Use `create(ConditionSchema)` to create a new message.
 */
export declare const ConditionSchema: GenMessage<Condition>;

/**
 * @generated from enum routeiq.v1.insights.Operator
 */
export enum Operator {
  /**
   * @generated from enum value: OPERATOR_UNSPECIFIED = 0;
   */
  OPERATOR_UNSPECIFIED = 0,

  /**
   * @generated from enum value: GT = 1;
   */
  GT = 1,

  /**
   * @generated from enum value: LT = 2;
   */
  LT = 2,

  /**
   * @generated from enum value: GTE = 3;
   */
  GTE = 3,

  /**
   * @generated from enum value: LTE = 4;
   */
  LTE = 4,

  /**
   * @generated from enum value: EQ = 5;
   */
  EQ = 5,

  /**
   * @generated from enum value: TREND_UP = 6;
   */
  TREND_UP = 6,

  /**
   * @generated from enum value: TREND_DOWN = 7;
   */
  TREND_DOWN = 7,
}

/**
 * Describes the enum routeiq.v1.insights.Operator.
 */
export declare const OperatorSchema: GenEnum<Operator>;

/**
 * @generated from enum routeiq.v1.insights.Severity
 */
export enum Severity {
  /**
   * @generated from enum value: SEVERITY_UNSPECIFIED = 0;
   */
  SEVERITY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: INFO = 1;
   */
  INFO = 1,

  /**
   * @generated from enum value: WARNING = 2;
   */
  WARNING = 2,

  /**
   * @generated from enum value: CRITICAL = 3;
   */
  CRITICAL = 3,

  /**
   * @generated from enum value: PAGE = 4;
   */
  PAGE = 4,
}

/**
 * Describes the enum routeiq.v1.insights.Severity.
 */
export declare const SeveritySchema: GenEnum<Severity>;

/**
 * @generated from enum routeiq.v1.insights.RecommendedAction
 */
export enum RecommendedAction {
  /**
   * @generated from enum value: ACTION_UNSPECIFIED = 0;
   */
  ACTION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: REDUCE_AUTONOMY = 1;
   */
  REDUCE_AUTONOMY = 1,

  /**
   * @generated from enum value: CIRCUIT_BREAK = 2;
   */
  CIRCUIT_BREAK = 2,

  /**
   * @generated from enum value: ESCALATE_HUMAN = 3;
   */
  ESCALATE_HUMAN = 3,

  /**
   * @generated from enum value: ROLLBACK_VERSION = 4;
   */
  ROLLBACK_VERSION = 4,

  /**
   * @generated from enum value: SWITCH_MODEL = 5;
   */
  SWITCH_MODEL = 5,

  /**
   * @generated from enum value: REQUIRE_APPROVAL = 6;
   */
  REQUIRE_APPROVAL = 6,
}

/**
 * Describes the enum routeiq.v1.insights.RecommendedAction.
 */
export declare const RecommendedActionSchema: GenEnum<RecommendedAction>;

