// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/dashboards.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file routeiq/v1/insights/dashboards.proto.
 */
export const file_routeiq_v1_insights_dashboards = /*@__PURE__*/
  fileDesc("CiRyb3V0ZWlxL3YxL2luc2lnaHRzL2Rhc2hib2FyZHMucHJvdG8SE3JvdXRlaXEudjEuaW5zaWdodHMihgEKD0Rhc2hib2FyZFdpZGdldBIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRISCgptZXRyaWNfaWRzGAMgAygJEi0KBHR5cGUYBCABKA4yHy5yb3V0ZWlxLnYxLmluc2lnaHRzLldpZGdldFR5cGUSFQoNZGVmYXVsdF9yYW5nZRgFIAEoCSJdCglEYXNoYm9hcmQSCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSNQoHd2lkZ2V0cxgDIAMoCzIkLnJvdXRlaXEudjEuaW5zaWdodHMuRGFzaGJvYXJkV2lkZ2V0KmsKCldpZGdldFR5cGUSGwoXV0lER0VUX1RZUEVfVU5TUEVDSUZJRUQQABIJCgVHQVVHRRABEg4KClRJTUVTRVJJRVMQAhIJCgVUQUJMRRADEgsKB0hFQVRNQVAQBBINCglTUEFSS0xJTkUQBUKYAQoxYnVpbGQuYnVmLmdlbi5zc2ZvcmdlLnJvdXRlaXEucm91dGVpcS52MS5pbnNpZ2h0c0IPRGFzaGJvYXJkc1Byb3RvWlJidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9pbnNpZ2h0cztpbnNpZ2h0c3YxYgZwcm90bzM");

/**
 * Describes the message routeiq.v1.insights.DashboardWidget.
 * Use `create(DashboardWidgetSchema)` to create a new message.
 */
export const DashboardWidgetSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_insights_dashboards, 0);

/**
 * Describes the message routeiq.v1.insights.Dashboard.
 * Use `create(DashboardSchema)` to create a new message.
 */
export const DashboardSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_insights_dashboards, 1);

/**
 * Describes the enum routeiq.v1.insights.WidgetType.
 */
export const WidgetTypeSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_insights_dashboards, 0);

/**
 * @generated from enum routeiq.v1.insights.WidgetType
 */
export const WidgetType = /*@__PURE__*/
  tsEnum(WidgetTypeSchema);

