// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/dashboards.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file routeiq/v1/insights/dashboards.proto.
 */
export declare const file_routeiq_v1_insights_dashboards: GenFile;

/**
 * @generated from message routeiq.v1.insights.DashboardWidget
 */
export declare type DashboardWidget = Message<"routeiq.v1.insights.DashboardWidget"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: repeated string metric_ids = 3;
   */
  metricIds: string[];

  /**
   * @generated from field: routeiq.v1.insights.WidgetType type = 4;
   */
  type: WidgetType;

  /**
   * @generated from field: string default_range = 5;
   */
  defaultRange: string;
};

/**
 * Describes the message routeiq.v1.insights.DashboardWidget.
 * Use `create(DashboardWidgetSchema)` to create a new message.
 */
export declare const DashboardWidgetSchema: GenMessage<DashboardWidget>;

/**
 * @generated from message routeiq.v1.insights.Dashboard
 */
export declare type Dashboard = Message<"routeiq.v1.insights.Dashboard"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: repeated routeiq.v1.insights.DashboardWidget widgets = 3;
   */
  widgets: DashboardWidget[];
};

/**
 * Describes the message routeiq.v1.insights.Dashboard.
 * Use `create(DashboardSchema)` to create a new message.
 */
export declare const DashboardSchema: GenMessage<Dashboard>;

/**
 * @generated from enum routeiq.v1.insights.WidgetType
 */
export enum WidgetType {
  /**
   * @generated from enum value: WIDGET_TYPE_UNSPECIFIED = 0;
   */
  WIDGET_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: GAUGE = 1;
   */
  GAUGE = 1,

  /**
   * @generated from enum value: TIMESERIES = 2;
   */
  TIMESERIES = 2,

  /**
   * @generated from enum value: TABLE = 3;
   */
  TABLE = 3,

  /**
   * @generated from enum value: HEATMAP = 4;
   */
  HEATMAP = 4,

  /**
   * @generated from enum value: SPARKLINE = 5;
   */
  SPARKLINE = 5,
}

/**
 * Describes the enum routeiq.v1.insights.WidgetType.
 */
export declare const WidgetTypeSchema: GenEnum<WidgetType>;

