// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/interventions.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_routeiq_v1_insights_alerts } from "./alerts_pb";

/**
 * Describes the file routeiq/v1/insights/interventions.proto.
 */
export const file_routeiq_v1_insights_interventions = /*@__PURE__*/
  fileDesc("Cidyb3V0ZWlxL3YxL2luc2lnaHRzL2ludGVydmVudGlvbnMucHJvdG8SE3JvdXRlaXEudjEuaW5zaWdodHMinAIKGkludGVydmVudGlvblJlY29tbWVuZGF0aW9uEgoKAmlkGAEgASgJEhUKDWFsZXJ0X3J1bGVfaWQYAiABKAkSEQoJbWV0cmljX2lkGAMgASgJEjYKBmFjdGlvbhgEIAEoDjImLnJvdXRlaXEudjEuaW5zaWdodHMuUmVjb21tZW5kZWRBY3Rpb24SEQoJcmF0aW9uYWxlGAUgASgJEhIKCmNvbmZpZGVuY2UYBiABKAESMAoMZ2VuZXJhdGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI3CgZzdGF0dXMYCCABKA4yJy5yb3V0ZWlxLnYxLmluc2lnaHRzLkludGVydmVudGlvblN0YXR1cypvChJJbnRlcnZlbnRpb25TdGF0dXMSIwofSU5URVJWRU5USU9OX1NUQVRVU19VTlNQRUNJRklFRBAAEgsKB1BFTkRJTkcQARILCgdBUFBMSUVEEAISDQoJRElTTUlTU0VEEAMSCwoHRVhQSVJFRBAEQpsBCjFidWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLmluc2lnaHRzQhJJbnRlcnZlbnRpb25zUHJvdG9aUmJ1Zi5idWlsZC9nZW4vZ28vc3Nmb3JnZS9yb3V0ZWlxL3Byb3RvY29sYnVmZmVycy9nby9yb3V0ZWlxL3YxL2luc2lnaHRzO2luc2lnaHRzdjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_routeiq_v1_insights_alerts]);

/**
 * Describes the message routeiq.v1.insights.InterventionRecommendation.
 * Use `create(InterventionRecommendationSchema)` to create a new message.
 */
export const InterventionRecommendationSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_insights_interventions, 0);

/**
 * Describes the enum routeiq.v1.insights.InterventionStatus.
 */
export const InterventionStatusSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_insights_interventions, 0);

/**
 * @generated from enum routeiq.v1.insights.InterventionStatus
 */
export const InterventionStatus = /*@__PURE__*/
  tsEnum(InterventionStatusSchema);

