// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/interventions.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { RecommendedAction } from "./alerts_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/insights/interventions.proto.
 */
export declare const file_routeiq_v1_insights_interventions: GenFile;

/**
 * @generated from message routeiq.v1.insights.InterventionRecommendation
 */
export declare type InterventionRecommendation = Message<"routeiq.v1.insights.InterventionRecommendation"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string alert_rule_id = 2;
   */
  alertRuleId: string;

  /**
   * @generated from field: string metric_id = 3;
   */
  metricId: string;

  /**
   * @generated from field: routeiq.v1.insights.RecommendedAction action = 4;
   */
  action: RecommendedAction;

  /**
   * @generated from field: string rationale = 5;
   */
  rationale: string;

  /**
   * @generated from field: double confidence = 6;
   */
  confidence: number;

  /**
   * @generated from field: google.protobuf.Timestamp generated_at = 7;
   */
  generatedAt?: Timestamp | undefined;

  /**
   * @generated from field: routeiq.v1.insights.InterventionStatus status = 8;
   */
  status: InterventionStatus;
};

/**
 * Describes the message routeiq.v1.insights.InterventionRecommendation.
 * Use `create(InterventionRecommendationSchema)` to create a new message.
 */
export declare const InterventionRecommendationSchema: GenMessage<InterventionRecommendation>;

/**
 * @generated from enum routeiq.v1.insights.InterventionStatus
 */
export enum InterventionStatus {
  /**
   * @generated from enum value: INTERVENTION_STATUS_UNSPECIFIED = 0;
   */
  INTERVENTION_STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: APPLIED = 2;
   */
  APPLIED = 2,

  /**
   * @generated from enum value: DISMISSED = 3;
   */
  DISMISSED = 3,

  /**
   * @generated from enum value: EXPIRED = 4;
   */
  EXPIRED = 4,
}

/**
 * Describes the enum routeiq.v1.insights.InterventionStatus.
 */
export declare const InterventionStatusSchema: GenEnum<InterventionStatus>;

