// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/slo.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/insights/slo.proto.
 */
export declare const file_routeiq_v1_insights_slo: GenFile;

/**
 * @generated from message routeiq.v1.insights.SloTarget
 */
export declare type SloTarget = Message<"routeiq.v1.insights.SloTarget"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string metric_id = 2;
   */
  metricId: string;

  /**
   * @generated from field: string workspace_id = 3;
   */
  workspaceId: string;

  /**
   * @generated from field: string tier = 4;
   */
  tier: string;

  /**
   * @generated from field: string target_expression = 5;
   */
  targetExpression: string;

  /**
   * @generated from field: string window = 6;
   */
  window: string;
};

/**
 * Describes the message routeiq.v1.insights.SloTarget.
 * Use `create(SloTargetSchema)` to create a new message.
 */
export declare const SloTargetSchema: GenMessage<SloTarget>;

/**
 * @generated from message routeiq.v1.insights.SloStatus
 */
export declare type SloStatus = Message<"routeiq.v1.insights.SloStatus"> & {
  /**
   * @generated from field: string slo_id = 1;
   */
  sloId: string;

  /**
   * @generated from field: string metric_id = 2;
   */
  metricId: string;

  /**
   * @generated from field: double current_value = 3;
   */
  currentValue: number;

  /**
   * @generated from field: double target_value = 4;
   */
  targetValue: number;

  /**
   * @generated from field: routeiq.v1.insights.SloState state = 5;
   */
  state: SloState;

  /**
   * @generated from field: double error_budget_remaining = 6;
   */
  errorBudgetRemaining: number;

  /**
   * @generated from field: google.protobuf.Timestamp evaluated_at = 7;
   */
  evaluatedAt?: Timestamp | undefined;
};

/**
 * Describes the message routeiq.v1.insights.SloStatus.
 * Use `create(SloStatusSchema)` to create a new message.
 */
export declare const SloStatusSchema: GenMessage<SloStatus>;

/**
 * @generated from enum routeiq.v1.insights.SloState
 */
export enum SloState {
  /**
   * @generated from enum value: SLO_STATE_UNSPECIFIED = 0;
   */
  SLO_STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MEETING = 1;
   */
  MEETING = 1,

  /**
   * @generated from enum value: AT_RISK = 2;
   */
  AT_RISK = 2,

  /**
   * @generated from enum value: BREACHED = 3;
   */
  BREACHED = 3,
}

/**
 * Describes the enum routeiq.v1.insights.SloState.
 */
export declare const SloStateSchema: GenEnum<SloState>;

