// @generated by protoc-gen-es v2.12.0
// @generated from file routeiq/v1/insights/slo.proto (package routeiq.v1.insights, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file routeiq/v1/insights/slo.proto.
 */
export const file_routeiq_v1_insights_slo = /*@__PURE__*/
  fileDesc("Ch1yb3V0ZWlxL3YxL2luc2lnaHRzL3Nsby5wcm90bxITcm91dGVpcS52MS5pbnNpZ2h0cyJ5CglTbG9UYXJnZXQSCgoCaWQYASABKAkSEQoJbWV0cmljX2lkGAIgASgJEhQKDHdvcmtzcGFjZV9pZBgDIAEoCRIMCgR0aWVyGAQgASgJEhkKEXRhcmdldF9leHByZXNzaW9uGAUgASgJEg4KBndpbmRvdxgGIAEoCSLbAQoJU2xvU3RhdHVzEg4KBnNsb19pZBgBIAEoCRIRCgltZXRyaWNfaWQYAiABKAkSFQoNY3VycmVudF92YWx1ZRgDIAEoARIUCgx0YXJnZXRfdmFsdWUYBCABKAESLAoFc3RhdGUYBSABKA4yHS5yb3V0ZWlxLnYxLmluc2lnaHRzLlNsb1N0YXRlEh4KFmVycm9yX2J1ZGdldF9yZW1haW5pbmcYBiABKAESMAoMZXZhbHVhdGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCpNCghTbG9TdGF0ZRIZChVTTE9fU1RBVEVfVU5TUEVDSUZJRUQQABILCgdNRUVUSU5HEAESCwoHQVRfUklTSxACEgwKCEJSRUFDSEVEEANCkQEKMWJ1aWxkLmJ1Zi5nZW4uc3Nmb3JnZS5yb3V0ZWlxLnJvdXRlaXEudjEuaW5zaWdodHNCCFNsb1Byb3RvWlJidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9pbnNpZ2h0cztpbnNpZ2h0c3YxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message routeiq.v1.insights.SloTarget.
 * Use `create(SloTargetSchema)` to create a new message.
 */
export const SloTargetSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_insights_slo, 0);

/**
 * Describes the message routeiq.v1.insights.SloStatus.
 * Use `create(SloStatusSchema)` to create a new message.
 */
export const SloStatusSchema = /*@__PURE__*/
  messageDesc(file_routeiq_v1_insights_slo, 1);

/**
 * Describes the enum routeiq.v1.insights.SloState.
 */
export const SloStateSchema = /*@__PURE__*/
  enumDesc(file_routeiq_v1_insights_slo, 0);

/**
 * @generated from enum routeiq.v1.insights.SloState
 */
export const SloState = /*@__PURE__*/
  tsEnum(SloStateSchema);

